### ISSUE TITLE
Can someone do ASUS K501UX configuration please?

### ISSUE THREAD

**Issue by ncoccato** [hirschmann/nbfc#103]
I can't find a way to set the fans of the K501UX, can someone do that file config please?

**Comment by ragekit** [comment]
you might have found out yourself but : from diverse source online and after a few test with the R&W app i can confirm that the Asus zenbook UX32LN config works for this model

Beware : the K051LX that is in the beta build does not work with the K501UX properly : CPU fan max speed is too slow, and one of the register overwrite (last panel in the config editor) is wrong

Only issue with the Asus zenbook UX32LN config is that the CPU and GPU fan are mixed up. But since they are configured the exact same way it does not matter. If you're a control freak like me you can copy the config and correct it.

Although beware : I'm not really sure of myself for ANY of this. I know it works pretty well on my K501UX but maybe there are ways to make an event better config. Gotta wait for @hirschmann tutorial for making configs

**Comment by ragekit** [comment]
If only Asus could properly set up their cooling system that would be a blast ... those computer are pretty expensive as is.

**Comment by hirschmann** [comment]
See [Contributing guidelines: Config requests](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests)
