### ISSUE TITLE
Literally doesn't work at all (keeps looping)

### ISSUE THREAD

**Issue by Pecacheu** [hirschmann/nbfc#1085]
**Describe the bug**
When I try to open "NoteBook Fan Control" after installing, it won't let me select a profile, it just keeps trying to select the previous profile, sets itself to "Read-Only" mode for a few seconds, I can't interact with any of the controls, then after a few seconds, it just goes back to disabled.

I tried deleting all the files in all directories for the app and reinstalling, same problem. When I look at the Nbfc Service in Windows Services, it just keeps opening and closing, over and over and over again... The application won't even uninstall. The uninstaller just gets stuck. (Instead I had to force close, disable and delete the service, and manually remove all application files)

**To Reproduce**
Install and open the application. (I'm using a 2020 HP Spectre x360 15t running latest Win 10 Pro)

**Expected behavior**
It's never worked for me so I don't know what it's supposed to do. Uh, work, I guess?

**System information**
 - Windows 10
 - Tried several of them, including latest 1.6.3
 
[NbfcServiceLog.txt](https://github.com/hirschmann/nbfc/files/6033173/NbfcServiceLog.txt)
[NoteBookFanControlLog.txt](https://github.com/hirschmann/nbfc/files/6033179/NoteBookFanControlLog.txt)

**Comment by Arzugar** [comment]
Hey, I comment here because I have the exact same issue.
And from issue #1077 it seems like we are not alone.

What I have found while looking at the task manager is that "**Notebook FanControl Service**" is getting interrupt
 constantly.
![Interrupted processus](https://user-images.githubusercontent.com/80141443/110195779-7b702d80-7e1e-11eb-98de-de5c7b6a69b1.PNG)
 At the same time I have noticed that the process "**Windows Error Reporting**" (coming from the file C:\Windows\System32\WerFault.exe) is activating and  deactivating constantly (every second) and filling the windows errors logs with hundreds of reports (see one of them in the attached files).
I have also found another log file in 
C:/ProgramData/Microsoft/Windows/WER/ReportQueue/Critical_NoteBookFanContr_7338fd826098df2cc0d05fff625528f529f4e72e_c178f231_084e5b1c-6da1-4b31-a9dc-1260263bed33/Report.wer (changed to a .txt so I can upload it) if that may help.



@Pecacheu and @VVYREX if you could check to see if you observe the same thing in the task manager that could be usefull to confirm we all have the same issue. And if it's the case maybe also changing the name of the issue to something more clear (like Notebook FanControl Service interruption or something like that). Thanks.

**System information**

- Windows 10
- Version 6.3
- Omen 15-ekxxx (intel processor)

Btw sorry for my bad english (I'm french), and finally to those who will take the time to help us, thanks and good luck.

[Windows error report.txt](https://github.com/hirschmann/nbfc/files/6094728/Windows.error.report.txt)
[Report.txt](https://github.com/hirschmann/nbfc/files/6094752/Report.txt)

**Comment by TomGreen2** [comment]
Hello, I have an Omen 15-ek0357ng and i think I have the same Problems with starting and stopping the Service "NbfcService" again and again. The "PID" is even changing.
If i type "Nbfc - stop" then the service stops to restart, until I start the service again.
Also when I create a new config and dont write anything.
Can I help here with any information?

**Comment by Pecacheu** [comment]
Yeah I think it's probably the same issue
I don't have any clue how to fix it though.

**Comment by dkeske** [comment]
I have the same issue. Did anyone look further into it?

**Comment by fristyr** [comment]
Have same issue...

**Comment by Koba02** [comment]
Same problem here on EK0022NL

**Comment by sathvikpurushotham** [comment]
Yep I have the same problem on Acer Predator helios 300 PH315-53

**Comment by guillaumearnx** [comment]
Same on EK004NF

**Comment by jorbig** [comment]
The same occurs on my HP Spectre x360 16-f1640nd... Any workaround?

**Comment by djoleglc** [comment]
the same for me

**Comment by mitat52** [comment]
same for me too

**Comment by theflorr** [comment]
same, any fix?
