### ISSUE TITLE
Configuration explanations

### ISSUE THREAD

**Issue by 3DiH** [hirschmann/nbfc#13]
I want to thank you for your work.
Can you explain how to make configs, detect fan registers, etc?(It will be great if you can make wiki, I can try to help you with wiki)
Why in configs for my Asus n550jv only one fan? This laptop has two fans, and different temperature sensors(according to Open Hardware Monitor)
Why some temperatures overlaps in configs?(like 50-65C = 28.6% and 60-70C = 57.1%)

**Comment by 3DiH** [comment]
it looks like your program control both fans togather

**Comment by hirschmann** [comment]
Yes, NBFC sets both fans to the same speed on some Asus notebooks, because according to some testers, this configuration results in the best temperature/noise ratio.

An explanation how to make configs and why the temperatures overlap inf configs can be found in the (slightly outdated) [user manual](https://onedrive.live.com/view.aspx?cid=6c34bd33ac55ce36&page=view&resid=6C34BD33AC55CE36!545&parId=6C34BD33AC55CE36!450&app=WordPdf&wacqt=undefined).

I'll try to create a wiki as soon as I have more free time. I would appreciate your help, because my English is far from perfet ;)

**Comment by hirschmann** [comment]
https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#config-requests
