### ISSUE TITLE
the tutorial wiki doesn't say how to "investigate" an unsupported model and add the proper values

### ISSUE THREAD

**Issue by orangpelupa** [hirschmann/nbfc#136]
so we with unsupported notebooks can investigate and made our own configs and upload (pull?) it to github.

**Comment by hirschmann** [comment]
I'm already working on a tutorial on how to create a config from scratch.
It will be finished soon (hopefully) :)

**Comment by believer-ufa** [comment]
Man, please make this tutorial, because i also want to try configure my laptop with you tool :) And don't have knowledge to do it.

**Comment by trs-mtn** [comment]
yeah, it would be great. how long it will take?

**Comment by hirschmann** [comment]
I plan to publish the tutorial after the release of NBFC 1.5 (stable) - mid December.

**Comment by ragekit** [comment]
Nice ! related to my comment on the k501lx. I tried using the ec probe but I just don't know what to test or where

**Comment by Desoxyribose** [comment]
Related question: Will the new manual Wiki-article include help on how to find the EC-adress for the advanced fan config?

For my Acer X349 I found out that 0xED=Write and 0xEC=read with value ranging from 01-07 (although is already with running fan on the lowest rpm so propably the range is 0-7).

When I change the value manually you can hear the fan speed up for parts of a second until the value is automatically reset. I assume the it is somehow locked on the auto controle mode. When I shorten the EC write/read intervals it works somewhat better´.

How do I set the fan controle mode to "manual" in order to find the "control mode address" and "manual value"?

Thanks in advance!

**Comment by ppo78** [comment]
Hi hirschmann,

Thanks a lot for your work ! Your application improve the fan management of my new Asus laptop. Unfortunatelly, I have had to create my own configuration because my laptop was not in the list (Asus UX410UA).

As other users, I would like to understand how to have the best configuration and I'm not sure to do the best actions. For the moment, I have just modified basic configuration (critical temperature) and the range values in the temperature theresholds panel, but I have a lot of questions... :
 
1. What is the read/write register and how to define best values ?
2. same questions for min/max fan speeds ?
3. same questions for other settings in this panel ?

I saw you have explained these parameters in the wiki but it's not clear for me.

4. In the temperature thersholds, is it recommanded to not intersec value ranges ? In the screenshot of the wiki, each fan speeds are in two different ranges ? So how your program can choose the good range ? In my configuration, I have decided to never intersect value ranges but is it the right way to do ?

5. How to know if we have one or two fans in the laptop ? I have a two core cpu but I think that there is only one fan in the laptop. So, I have to parameter one or two fans ?

6. What is the fan speed overwrite configuration ?

7. I have tried to use ec-probe.exe with the read or monitor options but I have this error : "Could not load EC plugin" => Is-it a bug ?

Thanks a lot for your answers !

**Comment by hirschmann** [comment]
Finally, I have finished the tutorial: https://github.com/hirschmann/nbfc/wiki/How-to-create-a-NBFC-config
Additionally, I also wrote an example of how to configure the temperature thresholds: https://github.com/hirschmann/nbfc/wiki/Temperature-threshold#example
