### ISSUE TITLE
Help with creating a config

### ISSUE THREAD

**Issue by p-aaditya** [hirschmann/nbfc#1360]
so i am actually trying to create a config for my acer nitro5 laptop having model no. AN515-58. 
i could find any recommended configurations to be working on my laptop and i heard about the ec-probe that comes with nbfc.
so i tried to use ec-probe but i couldnt find which was the read and write register. i was hoping someone could help me with that. 
![2023-08-27_11-55](https://github.com/hirschmann/nbfc/assets/143318960/f66a32e1-2b48-45e3-b69b-d2a56ac1375e)
this is the info before the fan started going
![2023-08-27_11-56](https://github.com/hirschmann/nbfc/assets/143318960/5cd9fb35-6724-4b0d-a0d4-325d9d07f2ce)
this is the info just after the fan started going
![2023-08-27_11-57](https://github.com/hirschmann/nbfc/assets/143318960/74a44160-0a79-4c59-9036-a4dbec0b3ee9)
and this is the info just after the fan switched off.
and the load given by ec-probe was not enough for my fan to start moving so i was running a tower of hanoi program in parallel to give load.
hopefully someone could help me figure out the read and write registors.
thank you in advance

**Comment by Oblithian** [comment]
I used the free utility from [rweverything.com](url). To make the EC registries accessible for even myself. 

Also there is this old manual: [https://vdocument.in/notebook-fancontrol-user-manual.html?page=1](url)

(I got stuck because, once I got everything in 'enable' just sets the fan to maximum. So I will try re-installing NBFC and see if the profile works then. *Update: I had been wondering where the sliders were, turned out at some point the window shrank too much, making the sliders disappear. Preventing me from seeing or turning the slider from 100% to auto. It works mostly now.)
