### ISSUE TITLE
Acer Nitro 5 AN515-54

### ISSUE THREAD

**Issue by h4rqq** [hirschmann/nbfc#1374]
Well, I've using the config file for a slightly older model than mine, the -47 one, but while doing some research I found out using config files from other models might be dangerous even if it works so, has anyone made a config file for this model already?

**Comment by h4rqq** [comment]
Or should I just don't mind about it?

**Comment by joelmathewthomas** [comment]
That is actually true. 

One time I was testing all the possible configs, and accidentally wrote something to a register, which caused my laptop to not charge anymore. 

But it was not a big deal, because I just turned off my laptop for 60 secs and then, pressed and held the power button for about 60 secs for a reset. That solved it. 

I don't think its that dangerous. You could maybe try some other configs, but expect shit like this to happen. Still a hard reset can help if anything goes wrong I guess. 


Also, my model is AN515-57,

So maybe you could try the `acer_predator_g3-572.xml` config.

Works great . Only issue , if I poweroff my system, then I would have to boot into windows and just only run Nitro fan control. Then reboot to linux, and it will work.

No need to do this for reboots .
