### ISSUE TITLE
ASUS ROG G751JY fan on 0% turns on with temp change.

### ISSUE THREAD

**Issue by javierdlg** [hirschmann/nbfc#149]
I've been monitoring my fan with your program and using the ASUS G751JY on the ASUS G751JY-DH71 works great, but I have noticed that when the temperature of the CPU changes the fan defaults to 16.6% and then back to 0. 

This is minimal but I found it important to notice for further improvements.

Either way, thank you for the effort placed into this program!

**Comment by RypeDub420** [comment]
This is because your up or down tempature is triggering a fan speed change.

Monitor your tempatures during these step changes.

Then, modify your config accordingly.

Step Up will spin the fans to the desired speed % once that tempature is hit. So for instance: once your temps hit 65 degrees, it'll spin up to 60%.

Step Down will spin down the fan to whatever % is defined once the temps have dropped and hit that value. For instance: if your Step Down temp is 58 degrees, even though the Step Up speed is 60 degrees: your temps need to hit 58 degrees in order to cause the Step Down in fan speed %.

Now: maybe you're having a similar bug and I read your post completely wrong: Users are reporting that even though the fan speed is reporting 0%: they are still spinning.

This is a known bug and @hirschmann will need to step in so that he can request the proper diagnostics in order to figure out what is going on.
