### ISSUE TITLE
is it possible to write to IO space using nbfc?

### ISSUE THREAD

**Issue by dude-sam** [hirschmann/nbfc#170]
Is it possible to write to IO space ? The system im working on changes the fan speed by writing to a single bit in a register in the IO space. Thank you

**Comment by hirschmann** [comment]
Currently not. Maybe I can help you if you provide some more information like, notebook model, OS and most importantly, how do you want to change the fan speed by only changing a single bit (just on/off?).

**Comment by dude-sam** [comment]
Thanks for your reply Hirschmann. My apologies for being so brief.

I am trying to control an external chassis fan for an intel NUC. The fan is controlled by custom transistor circuitry and can either be low or high. To switch to high I need to be able to switch bit 31 at base address 1E30 in the IO space (0 for low speed- 1 for high speed).  I can do this using RWeverything, but wondered if this functionality may be included in nbfc as RWeverything doesn't have any monitoring capabilities. 

Thanks

Sam

**Comment by hirschmann** [comment]
I guess the easiest way to do this would be to write your own plugin for NBFC.
Just implement [IEmbeddedController](https://github.com/hirschmann/nbfc/blob/master/Core/StagWare.FanControl/Plugins/IEmbeddedController.cs). The implementation could look like [ECWindows](https://github.com/hirschmann/nbfc/blob/master/Core/Plugins/StagWare.Plugins.ECWindows/ECWindows.cs) but instead of implementing _EmbeddedControllerBase_, you could would e.g. call _HardwareMonitor.WriteIoPort()_ in your implementation of _IEmbeddedController.WriteByte()_.
Unfortunately you have to hard code the base address because the interface doesn't allow addresses > 255.
