### ISSUE TITLE
./build.sh builds executable for the wrong architecture

### ISSUE THREAD

**Issue by regular** [hirschmann/nbfc#176]
I followed your build instructions for Linux on a 64bit machine running Arch Linux.

The resulting executable in Linux/bin/ReleaseLinux however fails to run:

```
[root@blume ReleaseLinux]# uname -a
Linux blume 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux
[root@blume ReleaseLinux]# ./nbfc.exe
-bash: ./nbfc.exe: cannot execute binary file: Exec format error
[root@blume ReleaseLinux]# file nbfc.exe
nbfc.exe: PE32 executable (console) Intel 80386 Mono/.Net assembly, for MS Windows
```

**Comment by hirschmann** [comment]
The resulting assembly is architecture independent CIL code. Your problem is, that the Linux kernel on your system doesn't know how to handle .net/mono binaries.

The solution: call nbfc like this: `mono nbfc.exe`
You could also register .exe files as a non-native binary, see http://www.mono-project.com/archived/guiderunning_mono_applications/

**Comment by regular** [comment]
Ah, I see! Thanks!
