### ISSUE TITLE
I hear the fan although NBFC reports Current fan speed 0%

### ISSUE THREAD

**Issue by MichaelRumpler** [hirschmann/nbfc#182]
I always have my notebook running beside me although most of the time I work on another computer. The notebook is on with only Outlook and Chrome running, but the display switches off after a few minutes.

Sometimes the fan of the notebook goes on and I check what it does. NBFC reports the temperature still below 50° and the target and current fan speed at 0.0% although I can hear that the fan is on (and sometimes quite fast).

I use a Asus Zenbook Flip UX360UAK with Windows 10.

**Comment by m-tach** [comment]
I have the same issue on UX32LN. Fans are constantly running on 100%, even with NBFC enabled and set to 0.0% (and core temp ~30C). 
Has anyone faced this issue before? Is it more likely to be HW or SW causing it? I have tried the regular things - reinstalling, disassembling chassis + new thermal paste, flashing BIOS, building under Linux.

**Comment by houseman2001** [comment]
Same with me!
I was successfully using nbfc already with Win10 on a Sony VAIO Fit 13A, Model SVF13N1C5E, until yesterday. For some reason nbfc has no effect anymore to reduce fan speed, even if it's enabled and target fan speed is 0.0%. I'm facing a constantly high fan speed now which seems to be worse than the original settings by Sony!
Before I was very happy with the attached config which was build for a Vaio Fit 14A: 
[SVF14N1C5E (2).txt](https://github.com/hirschmann/nbfc/files/836490/SVF14N1C5E.2.txt)
It normaly writes on Register 94 with a polling interval of 1750ms.
I upgraded on nbfc 1.5 but no difference.

Any glue about the root cause?
Thanks for any help!

**Comment by rdts** [comment]
Same problem here. I have a Yoga 2 Pro. It worked well with the "Lenovo Yoga 13 2191" profile until a couple of days ago. 

I updated to 1.5.1 - no change.

The situation is like this:
When the service is in read-only mode I can see the real fan speed, which is 100.4% for both fans all the time.
When the service is fully enabled target fan speed and current fan speed show both 0.0% even though both fans actually run at full speed.
