### ISSUE TITLE
Ability to turn fan on for a few secs when closing lid.

### ISSUE THREAD

**Issue by ngnh** [hirschmann/nbfc#196]
Didn't know where to put this, but i'd be nice if you could set to turn fan on for x secs when closing the lid and entering sleep. Just to blow some of the hot air out of the machine.

**Comment by hirschmann** [comment]
The latest version of NBFC already resets the EC before standby/hibernate, which usually makes the fan spin faster.
The problem is that if the transition into standby is too fast, the EC doesn't have enough time to react.

**Comment by henfri** [comment]
Hello,

I was about to request exactly this:
`NBFC already resets the EC before standby/hibernate`

But on my machine, it does not work, probably due to:
`The problem is that if the transition into standby is too fast, the EC doesn't have enough time to react.`

Is there any workaround? 

Best regards,
Hendrik
