### ISSUE TITLE
How to add support for my own laptop?

### ISSUE THREAD

**Issue by qqgg231** [hirschmann/nbfc#22]
Hi, i like the idea of this project. 

I have Acer V3-371 with WIndows. Could you tell me what I need to make this program to work with my laptop? 

Is proper XML sufficient to support my laptop? 

If yes, how can i find proper ReadRegister and WriteRegister values?

---

edit: There is some documentation: https://onedrive.live.com/?cid=6c34bd33ac55ce36&id=6C34BD33AC55CE36!450

**Comment by qqgg231** [comment]
I confirm that the config file for Acer Aspire S3 is working for Acer v3-371. 
I checked it in R&W utility also.

Thank you for this tool!

**Comment by hanzi2u** [comment]
I know this isn't the right place to post it but i don't where else to put it but i had this program for a long time then i upgraded to windows 10 but downgraded again and i had to install it again but it keeps saying you have sufficient permission to install this but i do have All the rights to install it, i even went into safe mode at gave it all the permissions needed but it still keeps giving me this and i can say my laptop is not supported but it works anyways and i risk it because it really helps my computer any suggestions?

**Comment by stteven** [comment]
hi someoe can add a config for hp DV7-6197 ? I tried with conf for pavillion dv6 but doesn't work, i see also with RW. It's hard to me find right value, thanks

**Comment by hirschmann** [comment]
See https://github.com/hirschmann/nbfc/wiki/How-to-create-a-NBFC-config
