### ISSUE TITLE
How do I identify the registry that controls fan speed?

### ISSUE THREAD

**Issue by smtrejo** [hirschmann/nbfc#246]
More than an issue mine is a question as I didn't find a better place to ask.

  I know there's a tool included to dump the EC regs to a text file. How do I know which are the ones that control the fan for my specific model?

  I'll try to make a config for a HP Pavilion dv7 1240us as from what I remember a while ago I tried the HP Pavilion dv6 config and didn't work for me. By the way, this model (dv7 1240us) doesn't have a "fan control service" (Windows service I assume) and the fan is a 2-wire connector (black and red), so speed's controlled by voltage provided by the motherboard.

  Thanks in advance.

**Comment by smtrejo** [comment]
I found this config for a DV7:

https://github.com/hirschmann/nbfc/issues/137

I'll give it a try and reply.

By the way, for other users, NBFC CLI (Notebook Fancontrol Command Line Interface) has a "recommend" command:

> hirschmann commented on Dec 30 2016
> 
> Btw the NBFC CLI is able to recommend configs:
> nbfc config --recommend

https://github.com/hirschmann/nbfc/issues/139

**Comment by kocane** [comment]
I've just found this software and I'm keen on getting it to work with my elitebook 840 G1. Non of the existing profiles seem to do too great a job. Some seem to read fan speed (and allow setting it), but setting the lowest fan speed isn't really all that quiet..

Our models aren't similar but if you discover more on how to create a config for an unsupported model, then please let me know. Right now I don't really know what to do with the EC probe dumps...

**Comment by smtrejo** [comment]
Hey @kocane , I'm also a newbie on the world of EC regs, but I found a post that could help. It consists on constantly checking the changing values at the EC table to determine the registers that control fan speed:  http://voltground.com/haven/threads/69/

[As I read at the manual](http://forum.notebookreview.com/attachments/notebook-fancontrol-user-manual-pdf.105862/):  

> Additionally on some notebooks there is a BIOS option named "fan always on while on AC power" (or similar).
> You have to deactivate this option in order to give NBFC the opportunity to completely deactivate the fan.

In your case maybe turning off this option at BIOS settings may suffice.

**Comment by kocane** [comment]
Thanks! I'll have a look at that post later tonight, I think.

My laptop does indeed have a function to _not_ force fan while on AC but it's really the on/off/on/off cycle that bothers me. It's nice when the laptop is fully quiet but sometimes a very low fan may be even easier to get used to.

**Comment by kocane** [comment]
Mmh, I give up for now. The read/write EC is correct and I can indeed adjust the fan speed in RW Everything, and I try to translate the max and min values into decimal and then put em into NBFC. It kinda works but it doesn't seem to have much regard for my auto-fan adjustments and also it seems to just live its own life sometimes, where I gotta shut off the laptop and pull out the battery for it to "reset".

That being said, I guess it is hardly relevant to your trouble :-P

**Comment by rwese** [comment]
@kocane it can be tricky to get the addresses right. if it fails to reset the automatic/manual mode the memory address or default/reset-value is likely wrong.

**Comment by kocane** [comment]
@rwese where can I tweak that?

**Comment by hirschmann** [comment]
Check out https://github.com/hirschmann/nbfc/wiki/How-to-create-a-NBFC-config

**Comment by mirh** [comment]
I also had a DSDT parser in the works. 
Anyway why are you using 5 years old iasl?

**Comment by hirschmann** [comment]
I couldn't find a more up-to-date version of the DSDT Editor linked in the tutorial, but imho it's still the best platform independent DSDT editor available.
If you prefer a more up-to-date iasl, just replace the version which is shipped with the editor with an updated one.

**Comment by mirh** [comment]
Oh sorry, I [thought](https://web.archive.org/web/20120519053449/http://www.insanelymac.com/forum/index.php?showtopic=223205) it was a tool of yours.

**Comment by hirschmann** [comment]
No problem :)
If you've finished your DSDT parser, please let me know!

**Comment by mirh** [comment]
\> finish exams
\> ~~relax~~ finish *another* parser for CPUID whatever
\> .... ?
\> profit!

**Comment by hirschmann** [comment]
Good luck with your exams :)

**Comment by kocane** [comment]
@hirschmann Made this work beautifully with my 840 G1 btw! Amazing tool, wish it was around back in the day with all them noise laptops I've had. It's especially great with this undervolted i7 since it floats around 45-55c in temperature but doesn't really go over 60 even when watching 720p video.  Before the fan would kick in at 50c so it was really a lot of on/off. Putting this to 65 ensures quietness most of the time :-3

**Comment by Tuimalila** [comment]
@kocane How did you get it to work. I also have 840 G1 and it is driving me and my coworkers crazy with the constant noise the fans make. I've tried this utility but sometimes it works and others it doesn't since it does not have a configuration for 840. Can you upload your configuration or did you use some preconfigured one?

**Comment by kocane** [comment]
@Tuimalila my 840 G1 configuration isn't perfect, the fan speed reading seems to be wrong most of the time but it works fine for me. I've primarily just used the tool to basically increase the temp my computer needs to reach before the fans kick in. How hot is your PC, I mean the fans kicking in at 50c is just enough to annoy me when I sit alone in a quiet room but in a work environment, I'm surpriced anyone hear it.

I've attached my configuration:
[HP EliteBook 840 G1.txt](https://github.com/hirschmann/nbfc/files/1836906/HP.EliteBook.840.G1.txt)
Rename txt to xml

Remember it wont help much if there's some proces thats using the CPU enough for it to rise to the 70c, which I've set to the temperature where the fans should kick in, instead of 50c. It was simply because the computer easily can idle at 45-55c with the fan off, if there's little CPU activity.

**Comment by Tuimalila** [comment]
@kocane Thank you very much.. Will try it out.

**Comment by theworm90** [comment]
Hi I followed your guide to identify the addresses in the EC table, but I can't understand how to identify the correct ones, I have an asus x555la laptop if anyone can tell me how to test with rw everything.

**Comment by theworm90** [comment]
> No problem :)
> If you've finished your DSDT parser, please let me know!
Hi I followed your guide to identify the addresses in the EC table, but I can't understand how to identify the correct ones, I have an asus x555la laptop if anyone can tell me how to test with rw everything

**Comment by xeniachile** [comment]
with rweverything I have detected the value 183 as possible speed but when trying to change it it returns to its original value

what's going on, any suggestions?
