### ISSUE TITLE
ASUS G501JW : program won't even launch

### ISSUE THREAD

**Issue by Sacharpie** [hirschmann/nbfc#258]
Hello guys,

I really enjoy nbfc since a pretty long time on my ASUS G501JW to avoid both fan being too loud and CPU throttling. I reinstalled Windows 10 two days ago, as I upgraded to a new SSD, reinstalled nbfc too, and suddenly, after my computer woke up from sleep, it won't launch anymore :(

As it was the last 1.5.3 beta, I uninstalled and tried the regular 1.5.0 but it didn't change anything. I don't know what to do next, as I tried to fix it with CCleaner and it was not even a bit more successful :(

**Comment by hirschmann** [comment]
Please install 1.5.3 again, try to start it and then attach the service's log file here (see https://github.com/hirschmann/nbfc/wiki/Files-and-directories-overview for where to find it)

**Comment by Sacharpie** [comment]
Hi and thanks for your answer,

I so reinstalled 1.5.3 (program still don't launch), here's the service log :
[NoteBookFanControlLog.txt](https://github.com/hirschmann/nbfc/files/1063699/NoteBookFanControlLog.txt)

**Comment by hirschmann** [comment]
That's the client log.
The service log should be at `C:\ProgramData\NbfcService\`

**Comment by Sacharpie** [comment]
Oops, sorry for being a huge noobie !

There it is :
[NbfcServiceLog.txt](https://github.com/hirschmann/nbfc/files/1063747/NbfcServiceLog.txt)

**Comment by hirschmann** [comment]
From your logs it looks like is running problems, but since the client can't connect, there must be a problem. I guess the service's settings file is corrupt.

Please try the following steps:
- open a powershell as Admin
- stop the NbfcService via `stop-service NbfcService`
- save `C:\ProgramData\NbfcService\NbfcServiceSettings.xml` somewhere, so you can upload it here later
- delete `C:\ProgramData\NbfcService\NbfcServiceSettings.xml`
- start the NbfcService via `start-service NbfcService`
- start the client (`NoteBookFanControl.exe`) and select a config

If this solves your problem, please attach `NbfcServiceSettings.xml` here, so I can find out what went wrong.

**Comment by Sacharpie** [comment]
Well, I think we have something there : I stopped the NbfcService and went to C:\ProgramData\NbfcService, but I only have "NbfcServiceLog.txt" and absolutely nothing else ! How is that possible ?

**Comment by hirschmann** [comment]
If you don't select a config, the service doesn't create a settings file.

**Comment by infinitepolygons** [comment]
I think I had this same issue; I have a G501VW however. If you are running MSI Afterburner, you need to update RivaTuner Statistics Server to 7.0.0, and then a conflict is fixed and NBFC can run.

**Comment by Sacharpie** [comment]
Thank you, this is precious ;)

Le 3 août 2017 à 07:34, infinitepolygons <notifications@github.com<mailto:notifications@github.com>> a écrit :


I think I had this same issue; I have a G501VW however. If you are running MSI Afterburner, you need to update RivaTuner Statistics Server to 7.0.0, and then a conflict is fixed and NBFC can run.
