### ISSUE TITLE
No configs appearing

### ISSUE THREAD

**Issue by ajayyy** [hirschmann/nbfc#270]
I restarted my computer, and now when I run the program, no configs appear.
![image](https://user-images.githubusercontent.com/12688112/27204532-c565b6e4-51f9-11e7-9086-b66812c81715.png)

They are still in the folder, and still appear in the config editor.

**Comment by hirschmann** [comment]
This happens when the client can't connect to the service.
Please check if the service is running (via powershell):
`get-service NbfcService`

If the service is running, check the status:
`nbfc.exe status`

Also, please upload the service log, see https://github.com/hirschmann/nbfc/wiki/Files-and-directories-overview for instructions.

**Comment by ajayyy** [comment]
@hirschmann Thanks for your quick reply, I just started up the service from task manager and it worked.

The service was stopped. I think it's because I didn't have start with windows enabled, and I just started it manually.

This program is awesome, thank you so much for making it :).
