### ISSUE TITLE
Make the program easier for dummies

### ISSUE THREAD

**Issue by 151bar151** [hirschmann/nbfc#273]
Hello, firstly I have to say I'm happy that I finally found a program that can control fan speed on my laptop.
But I have Asus N71Jq and there isn't official setup for this laptop. I tried to use config from Asus laptops that are supported, but they do not make my fan run to max RPM at 100%. From Speedfan (it can't control fan speed on my laptop) I know my fan can run at over 6000 RPM when needed but with NBFC at 100 % using some Asus config it runs around 5060 RPM.  I'd like to create my own, but I really don't understand the stuff in edit part of the program. Why we can't simply edit the config files like "write max RPM, write min RPM, write critical temperature"?

**Comment by hirschmann** [comment]
See https://github.com/hirschmann/nbfc/wiki/Basic-fan-configuration#maxspeedvalue

**Comment by 151bar151** [comment]
Yeah, and that's what I'm talking about. Why some inteager? Why not RPM?
I set it to 255, but fan speed RPM goes lower instead of higher. Which number should be here for reaching 6000 RPM?

**Comment by hirschmann** [comment]
Most ECs don't support RPM as fan speed input, but either [TACH counts](http://ww1.microchip.com/downloads/en/AppNotes/en562764.pdf), or [duty cycles](https://en.wikipedia.org/wiki/Duty_cycle).

Since the fan slows down if you increase the speed value, you are obviously manipulating a divisor (like TACH count). This means you have to input a low value to increase the fan's speed.
