### ISSUE TITLE
problem with HP ProBook 4540s

### ISSUE THREAD

**Issue by maslukov** [hirschmann/nbfc#3]
keyboard stops working (zero response to keystrokes) and cooler rotates at maximum speed

**Comment by hirschmann** [comment]
Please provide more information:
* Selected config
* Have you made changes to the selected config?
* Operating system
* BIOS version
* Is there a BIOS option like "fan always on on AC power"? (if this option exists, it should be disabled)

**Comment by maslukov** [comment]
Hi hirschmann!
1.Selected config - HP ProBook 4540s.xml
2. Have you made changes to the selected config? - No I haven't made...
3. Operating system - Win 8.1 pro (64-bit)
4. BIOS version -  F.60 A(15 Jan 2015) 
5. ...disabled

**Comment by hirschmann** [comment]
NBFC logs to the Windows EventLog. You can get all entries via powershell:
`Get-WinEvent -ProviderName NoteBookFanControlService | ? {$_.Level -le 2} | % {"{0}{2}{1}{2}" -f $_.TimeCreated,$_.Message,[Environment]::NewLine} > ~\Desktop\NBFC.log`

Sounds like the problem is the config itself. I will remove it from the repo if this issue cannot be resolved.
