### ISSUE TITLE
From "enabled" to "read only" after restart

### ISSUE THREAD

**Issue by soxfan82** [hirschmann/nbfc#303]
Hi,

This is a fantastic program, thank you so much for creating it. You've turned a notebook I hated using into one I love using. 

I have just one issue. Every time I restart my computer, it goes from "enabled" back to "read only" and I have to manually open the program to put it back. I have "start with Windows" and "close to tray" both checked.

Thanks!

**Comment by hirschmann** [comment]
Maybe your issue is caused by some [known incompatibility](https://github.com/hirschmann/nbfc/wiki/FAQ#are-there-any-known-incompatibilities-with-nbfc).
If this isn't the case, please update to _NBFC 1.5.3 beta_, try to reproduce the error and then attatch the [service log](https://github.com/hirschmann/nbfc/wiki/Files-and-directories-overview) here.
