### ISSUE TITLE
HELP PLEASE!!!!!!!

### ISSUE THREAD

**Issue by iKutas1** [hirschmann/nbfc#323]
The fan stops running when you take your laptop fan 100 speed

**Comment by hirschmann** [comment]
Obviously, your notebook is not supported:
#322
#321 

If you want to create a config yourself, please read https://github.com/hirschmann/nbfc/wiki/How-to-create-a-NBFC-config
If you have any problems, please provide enough information, otherwise nobody can help you. See https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#issues
