### ISSUE TITLE
Doesnt work after the Windows Fall Creator Update

### ISSUE THREAD

**Issue by kyouda** [hirschmann/nbfc#362]
After installing the new update , Just shows Disabled and 0 C . Is anyone facing this issue??

Also just as a side note , my laptop is acer aspire e5 575g , and i used to use the config for acer e5 471g , It worked , and the fan speed did change to whatever i set in the app , just wanted to know if using config for another laptop damages my CPU fan in any way or other??? Thanks a lot

**Comment by kyouda** [comment]
Starting the service through task manager fixed it. Cab anyone clear the second doubt??

**Comment by positron96** [comment]
Does not work for me either, but I had Windows 10 1703 from the start, so it never worked at all. My laptop is Asus UX430UA

**Comment by positron96** [comment]
Nervermind, I just did not select a profile at first (actually it is not obvious that I should). Now it's working.

**Comment by passitheape** [comment]
Thanks for the tip with starting NBFC from the task manager. I had the same issue that I couldn't select enabled and it showed 0 in the task bar. Now it works, but it doesn't show the temperature but I can live with that. 
Sorry, I probably can't answer your question, but I am using an Asus UX310UA and am using the UX305 config and its been working perfectly for 3 weeks now. I can only guess but I don't think that it would do any arm to the hardware, since you merely decrease or turn pff the fan speed and not increase it to more than usual for better temps.
