### ISSUE TITLE
Configuration File for HP ENVY x360 15-bp130ng - need help

### ISSUE THREAD

**Issue by macgrubi** [hirschmann/nbfc#409]
Hello and hi,
I have some problems to make a config file for my HP ENVY x360 15-bp130ng, because I am not so fit to check the details of this project.
Can anyone help me to create the right configuration file for my HP ENVY x360 15-bp130ng. 
It has an Intel Core i7-8550U and the full description ist found here 
[http://www.notebookinfo.de/produkte/hp-envy-x360-15-bp130ng/2pt00ea-abd/00033709/].
Maybe I can take one of the existing files, but I don't want to destroy my notebook.

Thank you 
macgrubi

**Comment by Faltenreich** [comment]
+1

**Comment by dan-and** [comment]
Hi @macgrubi and @Faltenreich 

I already build two configs for the Envy X360 13 Inch (Ryzen) and Envy X360 15 Inch (Intel) Notebooks. However I have no 2017's 15-BP Modell, but the new 2018's  15-CN Model. 

Would you be so kind and give my Config a try ? Since you guys have intel CPUs, the current beta of NBFC should be able to start up, you just need to download the config from my github repo at 
https://github.com/dan-and/nbfc/blob/master/Configs/HP%20ENVY%20x360%20Convertible%2015-cn0xxx.xml 

It would be great to hear from you if it also works on the 15-BP or if there is additional work to do. 

Cheers,

Daniel
