### ISSUE TITLE
Acer Predator Helios 300 (PH317-51)

### ISSUE THREAD

**Issue by jedi93** [hirschmann/nbfc#426]
Can someone make a config for the PH317-51 (-586M) ?

**Comment by Daniol71** [comment]
Safer bet would be try out the configs for similar Acer models. If one works even a bit it's easier to tweak to get it working.

If you're comfortable with using command line and editing registers, you can use the EC probing tool https://github.com/hirschmann/nbfc/wiki/How-to-create-a-NBFC-config

Finally, there might be simpler fan control programs available for your laptop model, such as HWinfo and SpeedFan.

**Comment by jedi93** [comment]
Trying around with different configs sounds good, but where to start? And if its "working just a bit" I still need to find values, right?

I looked into the EC probing tool a while ago for my current/older notebook (Lenovo G500s) but I think I'm too dumb (or probably just too lazy) to find something in the thousand of lines of code...

I'll try other programs but, again, with my Lenovo G500s those never worked even the slightest, so I don't have much hope.

**Comment by Daniol71** [comment]
If you can control the fans with the slider (for any of the configs) you just need to set the temperature thresholds and it will more or less work.

Otherwise, open up your laptop and find the EC chip, then google the datasheet for that particular chip. It's described in the Wiki. You might get lucky and find something that tells you which values control the fans.

https://github.com/hirschmann/nbfc/wiki

Good luck, let me know if you get it working.

**Comment by jedi93** [comment]
I'll try the configs, but I don't want to open the laptop cause it's brand new...

**Comment by jedi93** [comment]
The service can't be started, it just tells me "error 1067"

**Comment by Daniol71** [comment]
As I suspected, your laptop is a gaming laptop so Acer have their own software to control the fans. Stop testing the configurations and follow the instructions here.

https://us.answers.acer.com/app/answers/detail/a_id/47694/~/adjust-gaming-settings-on-predator-helios-300

If you're having issues with the fans you might need to reset the EC (because you've been playing around with the fan settings by testing various configs). If you need to do that, follow the instructions here. Under "Is there a way to reset my notebook if something went wrong?".

https://github.com/hirschmann/nbfc/wiki/FAQ

I recommend using first party solutions in the future as I'm only using NBFC because it's literally the only option for my laptop.

Have fun with your new gaming laptop :)

**Comment by Daniol71** [comment]
Obviously uninstall NBFC :P

**Comment by jedi93** [comment]
The thing is, I have the feeling that the PredatorSense doens't really do anything. If I have it on manual, sliders all the way on the left for both fans, they still go ape if I start a game and there seems to be no way to reduce the speed/noise while playing.

**Comment by Daniol71** [comment]
You're not supposed to play a game with the lowest fan settings though. It's a gaming laptop, it's gonna be loud. There might be some other fan controllers like MSI Afterburner etc. that give you a bit more control, but I honestly wouldn't recommend running the fans below the manufacturer settings when playing a game.

NBFC is more for running fans faster (to get better cooling) or, for light workloads, being able to turn off the fan (under a certain temperature threshold).

Honestly, can't stress this enough, you should probably stop messing with the fan settings. Would be a shame to fry your new laptop.

**Comment by jedi93** [comment]
But the fans are way too loud/fast just 20 seconds in a game. The temps are around 50° Celsius, there's no reason for this noise...

**Comment by Daniol71** [comment]
Then I don't know, contact Acer or make a post on an Acer forum. Nobody's gonna make a config specifically for your laptop unless you really wanna take the time and make it yourself. The developer has already stated in the FAQ that he doesn't make configs for people, so you might wanna mark this issue as "closed". If you ever get a working config you're welcome to upload it here.

**Comment by jedi93** [comment]
hm, I extracted the DSDT to dsdt.aml in Linux, but I can't decompile it, not in Linux and not with the DSDT editor (AE_not_exist)

**Comment by lestcape** [comment]
Maybe that help (Is not exactly the model you are looking for):
https://community.acer.com/en/discussion/574033/helios-300-ph317-53-72p5-rtx-2060-fan-stopping/p6
