### ISSUE TITLE
File Descriptor does not support writing

### ISSUE THREAD

**Issue by GTRONICK** [hirschmann/nbfc#439]
Hi!, today, I was trying to start the service with:
`nbfc start`
And the output gives:
`File Descriptor does not support writing`
And the service does not starts.
I have also navigated to /opt/nbfc, and tried:
`mono nbfc.exe start`
Which gives the same output.

**Comment by GTRONICK** [comment]
Ok, after reading some threads, I found the one located here: [ttps://github.com/hirschmann/nbfc/issues/436](https://github.com/hirschmann/nbfc/issues/436). I have renamed the file `ECSysLinux.dll` with:

 `sudo mv /opt/nbfc/Plugins/StagWare.Plugins.ECSysLinux.dll /opt/nbfc/Plugins/StagWare.Plugins.ECSysLinux.dll.old`

Then rebooted, and ran:
`nbfc start`
And the service started again!.

**Comment by marak8** [comment]
I'm using NBFC from AUR on Arch Linux. In my case, the service starts, but it doesn't seem to regulate the fans until I apply the workaround above (rename the DLL). After that, it's enough to

    systemctl restart nbfc

and fan quiets down.

**Comment by Magentium-Chris** [comment]
Confirmed this also. Renaming that plugin allowed it to start without issues. I was getting an error stating that the pid file could not be created. Wondering if that could also cause this?

**Comment by zetorian** [comment]
Worked for me as well. I had the pid file error Chris mentioned and the File descriptor issue.
Arch linux - 4.15.3-1 
Gigabyte p35w V3

**Comment by elisaado** [comment]
I have the PID file issue even when nbfc is working fine so idk if it's really that

**Comment by erkexzcx** [comment]
@hirschmann - Any chance you could fix this issue?

**Issue**: NBFC does not work on Linux. Says "File Descriptor does not support writing".
**Solution**: delete `StagWare.Plugins.ECSysLinux.dll` file. (see [this](https://wiki.archlinux.org/index.php/Fan_speed_control#Configuration_2))

Sorry but I do not know C# well - can't investigate on my own, but this workaround is **always** required and it always works.

**Comment by lss4** [comment]
The fix above is also needed on my laptop, ASUS ROG STRIX GL702ZC.

Is there a way to gracefully get around the issue if the plugin is not compatible with a given laptop? I mean, to disable the plugin if it turned out to be incompatible so deleting the dll would be unnecessary. Otherwise I'll always have to manually edit the PKGBUILD whenever there's an update on AUR (to delete the file during install process).

**Comment by erkexzcx** [comment]
https://wiki.archlinux.org/index.php/Fan_speed_control#Installation I stated it clearly :)

**Comment by bbaserdem** [comment]
I have the same problem; any updates on this? Deleting the dll does solve the problem; but if we could get a fix that would be much better.

**Comment by lss4** [comment]
It seems as of some recent build of nbfc (built from nbfc-git AUR), it could now run without deleting the offending DLL. And there's now a formal GL702ZC profile (previously the GL702VM profile is used as a best match).

Not sure if this is due to `ec_sys.write_support=1` parameter. I've put this argument for quite a long time in my system and back then this parameter did not solve the problem (the error persisted) and I certainly needed to delete that DLL to get nbfc running.

**Comment by bbaserdem** [comment]
From what I understand; the `ec_sys.write_support=1` command does undo some kernel lockdown features; leading to vulnerabilities. (Something I have read, don't quite understand.) Removing the offending dll for now seems to be the more prudent fix; please correct me if I am wrong.
