### ISSUE TITLE
HP Elitebook 8570W

### ISSUE THREAD

**Issue by jtojto** [hirschmann/nbfc#460]
Hi,
First thanks a lot for nbfc software, HP 8570W fan are noisy in a quiet room.  Fans are running at around 55°C.
I install nbfc and setup config file to let the CPU climb to 78°C. So fans get running seldom.

But at startup nbfc doesn't get the hand over the bios. I notice that I should launch Psensor and wait a little time for nbfc working well.

My config
HP Elitebook 8570W
Ubuntu 16.04 whith Cinnamon interface
nbfc 1.5.0

Have a nice day !

**Comment by bbildman** [comment]
I also have a 8570W, what config are you using because there is only Elitebook 8570W and 8760W included in nbfc.

Also Using the most recent beta 1.53 my Elitebook WIndows 7 abruptly closes down, I believe this is due to nbfc, because I was using nbfc 1.5 stable and this never happened. I will try using my Win 7 without the beta release, and see if this continue to happen.

Is there a config specifically for the Elitebook 8570??

Thanks

**Comment by bbildman** [comment]
So far after deleting 1.53 beta, my WIn7 system has been stable. I also reinstalled 1.50 Stable release, and my system also remains without any shutdowns. My conclusion is that the beta release somehow interferes with my laptop, causing intermittent shutdowns (the laptop simply shuts off)
