### ISSUE TITLE
"Could not acquire EC lock" on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by linkwh** [hirschmann/nbfc#472]
After having built and installed the software (1.5.2 and 1.5.3 beta) as explained on this website :
- the service seems to run fine
- nbfc.exe does not work in enabled mode and displays the error "Could not acquire EC lock"
NBFC ran just fine on the same computer with Ubuntu 17.10.

**Step 1 : start the service & check that the service is running** 
$ sudo systemctl start nbfc
$ sudo systemctl status nbfc
● nbfc.service - NoteBook FanControl service
   Loaded: loaded (/etc/systemd/system/nbfc.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2018-04-30 16:35:48 CEST; 11min ago

**Step 2 : read only mode works**
$ nbfc.exe start -r
$ nbfc.exe status
Service enabled		: True
Read-only		: True
Selected config name	: Asus Zenbook UX310UA
Temperature		: 34

Fan display name	: Fan #1
Auto control enabled	: True
Critical mode enabled	: False
Current fan speed	: 0.00
Target fan speed	: 0.00
Fan speed steps		: 8

**Step 3 : enabled mode does not work**
$ nbfc.exe start -e
EC initialization failed: Could not acquire EC lock
$ nbfc.exe config -a "Asus Zenbook UX310UA"
EC initialization failed: Could not acquire EC lock

**Additional info**
mono-complete   4.6.2.7+dfsg-1ubuntu1   amd64
Linux 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by MonteyMontey** [comment]
same issue for me

**Comment by Gele-CZ** [comment]
Same problem as @linkwh and @MonteyMontey. Tested on Ubuntu 16.04, 16.10 and 17.10 (everything OK), 18.04 not working with `EC initialization failed: Could not acquire EC lock`.

**Comment by stefanocirici** [comment]
Confirm this issue on 18.04 with UX430UQ.

**Comment by Gele-CZ** [comment]
@stefanocirici :+1: 

Disabled Secure Boot is already functional on my NTB (UX430UA).

**Comment by linkwh** [comment]
Mine is an Asus computer (UX410UA), juste like @stefanocirici and @Gele-CZ 
Could the problem be Asus-specific?

NBFC ran juste fine on Ubuntu 17.10 with secure boot enabled.

**Comment by linkwh** [comment]
In can confirm that it runs fine on Ubuntu 18.04 **without** Secure Boot disabled.

Any idea on how to make it work with Secure Boot enabled?

**Comment by stefanocirici** [comment]
@hirschmann could you please take a look at our problem? I would like to keep secure boot enabled.

**Comment by hirschmann** [comment]
I don't have much spare time right now, but I'll try to reproduce this issue on the weekend.
In the meantime, you could try to stop the service, then delete `nbfc/Plugins/StagWare.Plugins.ECSysLinux.dll` and restart the service.

**Comment by hirschmann** [comment]
Thanks for your fast response 👍 

The problem is caused by these "kernel lockdown" patches:
https://lkml.org/lkml/2017/4/5/652

In particular:

> * No use of ioperm(), iopl() and no writing to /dev/port.

The  [ECLinux ](https://github.com/hirschmann/nbfc/blob/master/Core/Plugins/StagWare.Plugins.ECLinux/ECLinux.cs)plugin uses `/dev/port/` to access the EC :(

> * Restrict debugfs interface to ASUS WMI.

The [ECSysLinux](https://github.com/hirschmann/nbfc/blob/master/Core/Plugins/StagWare.Plugins.ECSysLinux/ECSysLinux.cs) plugin uses `/sys/kernel/debug/ec/ec0/io` (debugfs) to access the EC :(
Actually the ECSysLinux plugin can only be initialized because it only checks if the [ec_sys](https://github.com/torvalds/linux/blob/master/drivers/acpi/ec_sys.c) kernel module can be loaded with write support enabled, but it should also check if it's actually possible to access the EC (this is a bug - I will fix it).

**The good news:**
There is a workaround, see #414 (@stefanocirici already posted this)
You don't have to completely disable secure boot. It's enough to "just" lift the kernel lockdown, see:
https://github.com/hirschmann/nbfc/issues/414#issuecomment-354274657
and
https://github.com/hirschmann/nbfc/issues/414#issuecomment-370253669

**The bad news:**
Currently, I don't know how to access the EC from user mode without lifting the kernel lockdown.
If someone has an idea, please let me know :)

**Comment by GitEscape** [comment]
I'm new to Mint 19 and can't get the #414 script from @jgoclawski to work?

mandree's method works for me (kernel.sysrq=16), but I'm unsure if my lift_kernel_lockdown.sh is booting properly, and none of the boot managers I've Googled for seem to be available for M19 at the minute. I'm fresh to Linux from Windows, so I don't even know if the syntax in my files is correct?

Another thought is that they might be plaintext files, although I C&Ped a genuine .sh to try and avoid that. It's not as easy to me as just creating a .bat and throwing it into Startup. Help appreciated!

**Comment by GitEscape** [comment]
I'm new to Mint 19 and can't get the #414 script from @jgoclawski to work?

mandree's method works for me (kernel.sysrq=16), but I'm unsure if my lift_kernel_lockdown.service is booting properly, and none of the boot managers I've searched for seem to be available for M19 at the minute. I'm fresh to Linux from Windows, so I don't even know if the syntax in the two files is correct for Mint?

Another thought is that they might be plaintext files, although I C&Ped a genuine .sh to try and avoid that. It's not as easy to me as just creating a .bat and throwing it into Startup. Help appreciated!

**Comment by GitEscape** [comment]
BUT... lift_kernel_lockdown wasn't recognised with systemctl is-enabled, so I copied NBFC.service to another directory, filled it with the script and renamed it, and then made sure it was executable via Permissions before moving it back. And that's done it!

Good work @jgoclawski

**Comment by Demetrio92** [comment]
For me, disabling secure boot worked.

**Comment by rijnhard** [comment]
have you tried adding the following kernel flag? `ec_sys.write_support=1`
