### ISSUE TITLE
After nbfc build:can't find the /ReleaseLinux directory?

### ISSUE THREAD

**Issue by liuyinz** [hirschmann/nbfc#491]
I have read the  [first step](https://github.com/hirschmann/nbfc/wiki/First-steps)
After you have built NBFC, copy the files from `nbfc/Linux/bin/ReleaseLinux/` to `/opt/nbfc/`
in the bin directory,I can't find the /ReleaseLinux ,it seems different with the /Release ?Am I missing any procedure of building ?
I try to cp the files from  /Release to /opt/nbfc/,but it just doesn't work.![screenshot from 2018-05-27 10-50-42](https://user-images.githubusercontent.com/35212403/40582047-2841ab08-619c-11e8-9e91-deb288d99733.png)
![screenshot from 2018-05-27 10-51-12](https://user-images.githubusercontent.com/35212403/40582048-2898c9ce-619c-11e8-95ec-a3846b4737e2.png)

**Comment by markusritschel** [comment]
You need to execute the ./build.sh

**Comment by gcvl** [comment]
I had almost the same problem: 1.5.0 did not build anything under nbfc/Linux and the bin folder was missing altogether. 1.5.3 put all the binaries under nbfc/Linux/bin/Release instead of ReleaseLinux.
I copied all the contents into /opt/nbfc, the service files in /etc/systemd/system, then enabled the service with sudo systemctl enable nbfc - - now and applied the config file with mono /opt/nbfc/nbfc.exe config - - apply [config file without extension] and all was right.
This is an awesome piece of software, the only one that allowed me to quiet down the cpu fan of my 8460p laptop.
Please keep it up!

**Comment by TainKung** [comment]
I also had that problem. Actually I guess an update on the installation guide is badly needed. The build.sh does build something, but they are clearly not in the right place given by the guide.

**Comment by hirschmann** [comment]
The part of the build config which copies the build output to Linux/bin/Release is broken in 1.5.0.
Just check out and build 1.5.3 instead.
