### ISSUE TITLE
SAMSUNG NP350V5C (MB:Compal LA-8861P) (EC: KB9012)

### ISSUE THREAD

**Issue by Alfazilla** [hirschmann/nbfc#500]
My laptop model, motherboard id and embedded controller id is as in the title. 

Link to datasheets of my motherboard and embedded controllers are given below:
Motherboard: "http://www.electrovasya.ru/lib/exe/fetch.php/notebooks/compal/compal_la-8861p.pdf"
EC: "https://reservice.pro/upload/Datasheets/kb9012qf.pdf"

I found EC id from the schematic of MB at p41.
After i figured out that my EC is "KB9012", i went to search with it and it turned a datasheet for my EC, which is also linked above.

Now at page 103 in the EC datasheet i can see the "Fan Registers Descriptions". 

But i did not understand how to use these values in NBFC config. Please help! My PC is burning!! :(

**Comment by dslul** [comment]
Hi, I managed to get full fan speed (I have the same laptop) with the script in this repo: https://github.com/neduard/acer_5750G_fan_maximiser

I guess this info could also be used for a config file. It writes 0x77 to port 0x68 for full speed, and 0x76 to return to normal speed.

**Comment by Fabix21** [comment]
@dslul , I have similar problem with np350v5c, but i can't use perl script since i using Windows. How these port 0x68 and write 0x77 translate to NBFC config? 

I tried to set write register to 0x66 (which it's 104 in dec) value, then set Read register to 0x77 (119), and set Max fan speed to 255. Unfortunately nothing happened at all.

But when i used prepared NBFC config for Acer Aspire V3-571G, which is reported by users of that script as working also. I could set fan speed but only in range of 0 to somewhere 30% but when i push more fan doesn't speed up. For Acer config, write and read register is set to 180.

**Comment by dslul** [comment]
@Fabix21 you can compile the cpp program, it was made for windows.
I tried the same thing as you did but had no luck with those nbfc configs, I guess the EC firmware in our PC is a bit different from the Acer one.
Maybe reverse engineering it could help, after all it's only 128KiB of code (or even simpler, looking at the acpi?)

**Comment by Fabix21** [comment]
@dslul acually it was 1st thing that comes to my mind, i wanted to compile it and export to exe from my pc, but i had some compiler errors so i leaved it untill now. 

I fixed these minors compiler errors, exported exe and run this scrpit. I got message: Unable to open LPC driver. Error 0x2, which later on lead me to solve this fan issue. 

So i ill share that info maybe someone still struggling with these samsung laptops. By googling it i found another GitHub project called Acer Fan Control by @jaryn-kubik In his repo you can find drivers provided by acer (which working on samsung laptop since EC is same). And after you install it you ill be able to run your fan at max speed, using script or his program which is more convenient.
