### ISSUE TITLE
The type or namespace name `NLog' could not be found.

### ISSUE THREAD

**Issue by reifnotreef** [hirschmann/nbfc#513]
Currently using Fedora 28, have updated mono-devel via http://www.mono-project.com/download/

`FanControl.cs(1,7): error CS0246: The type or namespace name `NLog' could not be found. Are you missing an assembly reference?
	Plugins/FanControlPluginLoader.cs(1,7): error CS0246: The type or namespace name `NLog' could not be found. Are you missing an assembly reference?
	FanControl.cs(39,33): error CS0246: The type or namespace name `Logger' could not be found. Are you missing an assembly reference?
	Plugins/FanControlPluginLoader.cs(12,33): error CS0246: The type or namespace name `Logger' could not be found. Are you missing an assembly reference?

	 4 Warning(s)
	 4 Error(s)`

Formatting of the error is a bit wonky.
Did some googling and NLog appears to be a .NET logging library. Not sure to install/update it on Fedora.

**Comment by TainKung** [comment]
Hello,
I've met the exactly same problem. The root cause is that the latest version of nuget.exe fails to read dependencies from `NoteBookFanControl.sln`, which will leave critical packages uninstalled and then cause failures in building.
My workaround is to download nuget.exe manually from https://www.nuget.org/downloads (v4.1.0 works, haven't tried other versions). After it's downloaded, forget `build.sh` but just run:
```
# mono nuget.exe restore
# xbuild /t:Build /p:Configuration=ReleaseLinux NoteBookFanControl.sln
``` 
Now you can continue your installation : )
