### ISSUE TITLE
Add support for the HP Envy X360 15-bq102ng with Ryzen 2500U and a question

### ISSUE THREAD

**Issue by KookyBone** [hirschmann/nbfc#565]
Hello,

first a question. When i apply a profile will it be always active? Or only when i start the software. Can i go go back to the original state if there is a problem?

And than i really appreciate what you guys are doing.... good work and really a needed part of Software that should be standard in every Laptop. 

But can you please add the HP Envy X360 15-bq102ng with Ryzen 2500u as a profile? I just read you added an profile for the smaller 13 inch Version (THX for the guy who has made this). Is it possible to try this without a risk? Which Software do you recommand to check the temperatures? And is there an easy way to edit the profile if something is wrong?

**Comment by dan-and** [comment]
Hi @KookyBone ,
It was me. You can also try the 15-CNxxxx version, which does have the same fan size as the 15-bq102ng.
It should be relatively safe. I still try to get my hands on an original 15-bq102ng to fine tune the fan speed output, but it should fit nicely.

**Comment by KookyBone** [comment]
THX @dan-and ! I will try it the next days and will report back to you.

**Comment by dan-and** [comment]
@KookyBone and?

**Comment by paganisrock** [comment]
> @KookyBone and?

Not the original person, but my x360 15 inch with the 2700u works perfectly with that profile. The only issue I can find is that setting the speed to 100% only results in around 95% fan speed.

(I have the later x360 with the vent on the side, not the rear.)

**Comment by dan-and** [comment]
@paganisrock That's something which should be easy to solve! 

Have some something that powers your CPU to the max quickly (i.e. prime95 cpu torture or a tough benchmark) ready. 

Go into Notebook Fan Control and switch to Read-Only Mode. 

Windows Key + R , then enter cmd to open a command line interface. 
Enter: 
ec-probe monitor --clearly -r ec-probe-report.txt
It will monitor all EC-Registers for this test and save them to "ec-probe-report.txt" at the end. 

Start the Application that stresses out your CPU so that it will run at 100% Fan-Speed. If you think the Fan can not run higher, stop the Application and go back into the command line interface. 

Press CTRL+C to stop the monitoring. 

Now you have a report called "ec-probe-report.txt". You can open it in any editor. You can paste the results or upload the file here to figure out the min and max value.

Good Luck! 

Dan
