### ISSUE TITLE
New branching model

### ISSUE THREAD

**Issue by hirschmann** [hirschmann/nbfc#567]
With the latest beta release, I have updated the branching model.

Up until now, there was only one public branch (master) which acted as the "stable most of the time" branch. This branching model was pretty shitty because users and package maintainers couldn't be sure theat the master branch is stable and I couldn't publish new stuff as fast as I wanted.

Therefore I've introduced two new public branches, so from now on there will be 3 different branches:

- **stable**: for stable releases only (obviously)
- **beta**: for beta releases and preparing stable releases
- **master**: the public integration branch (default branch for pull requests). think of it as an alpha branch

If you have suggestions for improvements, please let me know 😄

**Comment by hirschmann** [comment]
@erkexzcx This might interest you

**Comment by erkexzcx** [comment]
> @erkexzcx This might interest you

Heh, sure it is! I will push some updates to Arch Linux AUR.

The only question is - How about config profiles? I have few ideas:

A) Only 3 complete packages - Stable, Beta and Development.
B) 4 packages - Stable, Beta, Development packages without config profiles and separate package named "nbfc-configs" marked as a dependency for all 3 mentioned packages. Configs will be taken from Development version, since we want them as up to date as possible.

Thoughts?

**Comment by hirschmann** [comment]
Pushing not very well tested configs out to users of stable (or semi-stable) versions will cause havoc sooner or later.
There might also be configs on the master branch which rely on features which haven't been pushed to beta/stable yet.

I would opt for option **A** and a faster release cycle.

**Comment by erkexzcx** [comment]
Sure just give me few days to get those packages into AUR.

I just wanted to know if there are any new features planned/implemented? What is the purpose of making these new branches?

**Comment by hirschmann** [comment]
Take as much time as you need. Thanks for packaging NBFC for the AUR :)

I have planned several changes which are potentially breaking:

- switch from OpenHardwareMonitorLib to LibreHardwareMonitorLib for the Windows plugins (see #536)
- implement a REST API for the service (see #531). I'm also thinking about dropping the WCF endpoint.
- improve the plugin and config system

All this stuff is much easier to implement when I'm able to push it to the master branch and get feedback early in the development process without having to keep the master branch stable.

**Comment by erkexzcx** [comment]
Thanks for explaining me this!

FYI - I just recently pushed some updates to nbfc and nbfc-git packages to AUR. Unfortunately, [I consulted](https://bbs.archlinux.org/viewtopic.php?id=241056) Arch Linux Forums in regards of having multiple versions of NBFC app in AUR and final decision was 2 versions - stable & development (because there is no need to have more nbfc packages in AUR, right?). So basically this is what I am going to continue supporting:

- [nbfc](https://aur.archlinux.org/packages/nbfc/) - Your releases on GitHub.
- [nbfc-git](https://aur.archlinux.org/packages/nbfc-git/) - Default (development) branch.
