### ISSUE TITLE
weird temperatures display with 1.6.2

### ISSUE THREAD

**Issue by nybbles2** [hirschmann/nbfc#591]
**Describe the bug**
After updated to 1.6.2 beta, my temperatures stopped working.

See: https://github.com/hirschmann/nbfc/issues/127

**To Reproduce**
update to 1.6.2

**Expected behavior**
I expected it to work properly. After messing around I was able to get 1.6.1 to work again. But oddly enough, only after installing and uninstalling HP Notifications, which came through the HP Support Assistant.

I was able to reinstall HP Notifications, and have 1.6.1 work.  But 1.6.2 seems to somehow make it stop working.

I can repeat the process. HP Notifications once installed will mess up 1.6.2. But, going back to 1.6.1 without first uninstalling HP Notifications will cause 1.6.1 to also display the negative temperature, etc.

I should make it clear that 1.6.2 does not work regardless whether HP Notifications is installed or not installed.

So, I don't think HP Notifications is the cause... So confused. 

**System information**
 - Windows 10 Pro 
 - HP ZBook Studio G5 (seems to work great with the Studio G3 profile)
https://support.hp.com/us-en/drivers/selfservice/hp-zbook-studio-g5-mobile-workstation/18865653
 - NBFC version (see above)
 - log files (see [NBFC files and directories overview](https://github.com/hirschmann/nbfc/wiki/Files-and-directories-overview))

**Additional context**
Please let me know if you have any ideas why it would do this? This seems to be the only Fan Control software that works with the Studio G5. SpeedFan just doesn't see the fans at all. I need this software because the fans can get really loud for no apparent reason (and the system never goes over 80 C). Fans can ramp up even when in the high 60s (which is overkill on the cooling system - isn't max temp for this particular CPU 100%???) All other temps are well under the CPU temps.

**Comment by gandreou** [comment]
Similar problem on an HP Spectre.

I know the profile works since I've manually tested the register, but the temperature reading is incorrect/stuck at  -2147483648°C, so it won't trigger.

@hirschmann, any ideas ? Apparently, something is zeroing out. I'd really like to use your software and I'm willing to buy you a beer :-)

In my case, I tried uninstalling HP Assistant/Solutions Framework and using different versions of NBFC (from 1.5 to 1.6.3) but the temperature is always incorrect.

@nybbles2 does 1.6.1 still work for you if you uninstall the HP bloatware ?

**Comment by hirschmann** [comment]
@nybbles2
The NBFC 1.6.2 beta setup isn't able to update some files if a previous version of NBFC is installed on the system.
This could explain the behavior you described.
You could give 1.6.3 stable a try or just stick with 1.6.1 if everything works fine.

@gandreou
According to the log, the driver is marked for deletion:
>Status: Installing driver "E:\openhardwaremonitor-v0.8.0-beta\OpenHardwareMonitor\OpenHardwareMonitorLib.sys" failed and file exists
First Exception: CreateService returned the error: The specified service has been marked for deletion. (Exception from HRESULT: 0x80070430)

Maybe a reboot is required to delete the driver. If it doesn't work, try to remove _WinRing0_ with autoruns (https://docs.microsoft.com/en-us/sysinternals/downloads/autoruns).
Also try to remove other hardware monitoring software before installing NBFC.

**Comment by gandreou** [comment]
Thanks for looking into this @hirschmann.

I actually restarted right after I wrote this comment, and the temperature reading worked, however, there is still some weirdness going on.

After some research and testing I feel I have a better understanding of what's going on.
It seems to be related to me using Throttlestop that utilizes the same winring0 service (that's why the service was already running according to the Openhardware log). I din't see this listed in the incompatibility list, so I didn't think about it at first.

The weird part is that if I install and run NBFC while Throttlestop is running, bd-prochot is triggered and the CPU throttles down to its minimum frequency. Installing NBFC first and Throttlestop afterwards, seems to fix this. However, if I load the NBFC taskbar icon, then randomly at some point it triggers bd-prochot again. In both scenarios the CPU is fairly cool (~43C).
I suspect that I'm running into some sort of deadlock situation where HP's power management, NBFC and Throttlestop are trying to read and manipulate registers at the same time, and the laptop enters some sort of safe mode.

Interestingly, if I let the NBFC service enabled in the background, without a task bar icon, bd-prochot doesn't trigger.
Any ideas how the task bar icon could be responsible for this ? I assume that the icon's temperature refresh rate is the same as the polling interval.

Some other ideas and comments:
- Have you thought about adding a "timer" feature similar to speedfan, that allows temperature to be above/below a threshold for a certain amount of time before triggering a fan speed change ? This would prevent the fans from going on/off, which can be annoying, when the cpu gets a short burst of load. I understand this can somewhat be achieved indirectly through the polling interval, but the timing is inconsistent since it depends on the randomness of when the cpu is loaded vs when the temperature is polled.

- I was reading in the Throttlestop forums that Windows 1903 enables memory integrity by default, which breaks winring0. You may want to look into that.

P.S.: Enjoy your beer !
