### ISSUE TITLE
Combobox config selection is empty

### ISSUE THREAD

**Issue by user8123** [hirschmann/nbfc#611]
I install nbfc on my Lenovo E520 with Windows 10 1809 64 Bit.
The service is running, but i cant enable the fan control an the config selection combobox is empty.

i try different versions, 1.5.0, 1.5.3 beta, 1.6 beta1 and 1.6 beta2, always the same issue.
Before i install an another cersion, i clean the config directorys in userpath and appdata.

I attached the logfiles, i hope this files help to solve the problem

[NoteBookFanControlLog.txt](https://github.com/hirschmann/nbfc/files/2708925/NoteBookFanControlLog.txt)
[NbfcServiceLog.txt](https://github.com/hirschmann/nbfc/files/2708926/NbfcServiceLog.txt)

**Comment by FalconFour** [comment]
Extremely weirded out, because I just got an E420 here (same exact generation/model, just the 14" version), and ran into this very odd issue. There are no profiles to pick from at all, and the app can't be enabled. I was expecting to be able to use the ThinkPad T430s profile, which works on all the ThinkPads I've tried it on so far (T500, T430, T430s, T530, W530), and would hope it'd work here the same. Really should just be renamed "ThinkPad generic 1" or some such - the bitmask it's manipulating is well documented (http://www.thinkwiki.org/wiki/How_to_control_fan_speed#Hardware_specs).

I started first by installing the latest 1.6-beta2, then when I ran into the problem, removed that and installed 1.5.3, also a blank configs box.

Without any configs populated and no "add" button, it completely breaks the program! 😮
