### ISSUE TITLE
HP Omen 17-w121tx

### ISSUE THREAD

**Issue by naive555** [hirschmann/nbfc#642]
I use **HP Pavilion 17-ab240nd** config which is change value of the temperature can change fan speed. Sometimes cause false reading temperature because I change the value over 90 c, so my laptop will hibernate. I just want to config fan speed directly but I cannot find better than this one. PS, the register is on 0x88 but it's not the fans, it's **acpi temp** so, I set temp to 90 c in % that make the fan bump to 3200 rpm. The max fan speed of this model is 5000 rpm. I cannot set to it yet.

**Expected Behavior**
Fan speed reach full 100%

**I currently use NBFC version 1.6.2 beta**

**Comment by naive555** [comment]
Updated. I found out the @179 and @178 are the registers to read fan speed but I cannot find the register to set fan speed.

**Comment by pwnerandy** [comment]
I am getting the same issue on my OMEN by HP Laptop 17-an0xx - It successfully bumps my fan to 4100/4200 rpm and works great. But I am getting hibernation shutdowns - event viewer reading "Kernel Power event 88" hibernation due to critical thermal event

It will shutdown sometimes when NBFC is enabled and not running max speeds, even just my computer idling will sometimes trigger this thermal hibernation. I Need help as well :D
