### ISSUE TITLE
Put 'selected config' into options

### ISSUE THREAD

**Issue by jojoTheBearded** [hirschmann/nbfc#677]
First up, many thanks- nbfc does _exactly_ what I needed, it does it in a great way, and it does no unneccessary other stuff than that! I already bought you a beer! :)

There's only one really small issue- can't the 'selected config' be moved into the 'settings'-window? Since it's a thing I set once and then forget about it, it's kind of irritatting that it is so prominently placed right at the top of the main window, taking up 'valuable screen estate' and demanding an, albeit small, amount of attention every time I look at the window...

I'm a huge sucker for sleek interfaces :) so another great (imho) idea would be to make the interface kind of skinnable- I imagine a small, black window without any frame or decoration...

Anyway, that was my small issue. Thanks again and enjoy the beer :)

**Comment by hirschmann** [comment]
Thank you for the beer and also for your suggestions!

I think it's important to show the selected config to the user in a prominent place, because it could be changed automatically e.g. because the user created a task which switches to a more silent config once the laptop is removed from the docking station.

Therefore I will not remove it from the main window. But if you have a suggestion of how to make it less distracting I'd like to see it :)
It would be nice if you could explain your design ideas or draw a mock up.
