### ISSUE TITLE
HP 15 - bs109

### ISSUE THREAD

**Issue by mrDevGo** [hirschmann/nbfc#688]
Good afternoon, I bought a laptop HP 15 - bs 109. A fan makes a lot of noise. There is no such configuration in your program. Help please please.

**Comment by mrDevGo** [comment]
[DSDT.txt](https://github.com/hirschmann/nbfc/files/3193864/DSDT.txt)

**Comment by webloft** [comment]
The DSDT looks familiar to my model which I decoded, so you can try this:
```

OperationRegion (ECMP, SystemMemory, 0xFF000000, 0x1000)
...
FRPM, 8 // FAN RPM (Read), 8bit
FNTV, 8 // FAN RPM (Write), 8bit
RSTV, 8 // Manual Mode Switch, 8bit
FNMN, 8 // FAN Minimal RPM, 8bit
FNMX, 8 // FAN Maximal RPM, 8bit
```

So which EC register you may set? This is tricky, because there are other names of the EC value than the RAM values but it seems that the EC memory is mapped (mirrored) in the RAM, so if you open ReadWrite Everything and open Memory and EC windows you may see the same values in EC and RAM at offset FF000808. It may differ but you can calcuate from the DSDT offset statements and translate it to the EC register offsets.

Then you have to set RSTV to anything other than 0x00 to enable the manual mode and try out values for FNTV. FRPM should follow these values roughly.

**Comment by Overc1ocker** [comment]
Try these values:[ New HP Laptop config]( https://github.com/hirschmann/nbfc/issues/1111)
