### ISSUE TITLE
Configuration for ASUS Zenbook UX480

### ISSUE THREAD

**Issue by Mouf25** [hirschmann/nbfc#695]
Hi all,

I'm not sure this is the right place to post my request but is anyone who can help me configure notebook fan control for an ASUS Zenbook Pro UX480 ?
I tried several configs but noone worked properly.

Thanks a lot !!

**Comment by benayat** [comment]
for future reference - 
same problem here. my fans won't work unless the temp is 90c or higher. 
I replaced the cpu thermal paste(which was very dry, probably due to a lot of heat) on the cpu and the gpu, and it actually decreased the temps by 30c. from 75c idle to 45c. the fans still aren't working though, so I'll probably have to repeat this process once a year.
it's a shame they didn't bother to make the fans programmable for this model.
