### ISSUE TITLE
OMEN by HP Laptop 17-an0xx With NBFC enabled, I get random hibernation with event viewer stating - "Kernel Power event 88"

### ISSUE THREAD

**Issue by pwnerandy** [hirschmann/nbfc#726]
**Describe the bug**
I am using HP Pavilion 17-ab240nd on my OMEN by HP Laptop 17-an0xx.
I have max speed set to 90 which tricks the processor/fan into thinking its 90c and runs at 100%. It works great and reduces my temps by a huge margin. BUT

I am getting random hibernation happening under high load or idling the computer. Even when the Fan is running at low % and temp reading is low. The event viewer is reading 

"Event 88 Kernel Power
The system was hibernated due to a critical thermal event.
Hibernate Time = ‎2019‎-‎07‎-‎12T17:49:51.302111200Z             
ACPI Thermal Zone = \_TZ.TZ01             
_HOT = 373K"

_Additionally -_ When the NBFC max speed is set to 90 to imitate the ACPI temp at 90c and get the fan to max speed, I am also getting these errors in event viewer - 

event 13 - ACPI : The embedded controller (EC) did not respond within the specified timeout period. This may indicate that there is an error in the EC hardware or firmware or that the BIOS is accessing the EC incorrectly. You should check with your computer manufacturer for an upgraded BIOS. In some situations, this error may cause the computer to function incorrectly.

I also tried to reinstall windows completely and it still is happening with NBFC enabled, so it wasn't anything to do with a windows update I guess.

**To Reproduce**
Enable Notebook Fancontrol with HP Pavilion 17 config with max speed at 90, use computer or let it idle and it eventually hibernates and gives this error in event log.

**Expected behavior**
I don't understand why I am getting a thermal shutdown when the processor is not getting near the temps required for that (100c). I only have it set to read up to 90c so it shouldn't be shutting down anyway, but still does at low temps. 

**System information**
 - Windows 10
 - NBFC version
- I am having trouble locating the logs. 

**Additional context**
Please help! I would love to run NBFC and keep the temps its giving me, but these shutdowns are very worrying and annoying.

**Comment by pwnerandy** [comment]
Update - I have tried different settings and not allowing the fan/acpi temp to go up to 90c. 

I have found that it will still cause the kernel power 88 thermal shutdown even if the PC is idle,fan is running at a low % with temps below 50c. It seems that something with NBFC is causing the error so for now I will stop using it and just turn off turbo boost. 

Hopefully someone knows of a fix, if I could just get NBFC to work without these thermal event issues it would be great to be able to use my components to their fullest potential.

**Comment by aleksamagicka** [comment]
I'm facing the same problem. Though I sometimes get a 'no battery present' message too.

According to the last post from [here](https://answers.microsoft.com/es-es/windows/forum/all/windows-10-kernel-power-error-88/6465742d-b5ee-4977-963a-7fc9283e3f32), the problem is in the Intel chipset driver. Try reinstalling the stock one.

Haven't tried this.

**Comment by iZN1337** [comment]
Yes, I'm getting this issue as well. Would like to have this sorted out somehow. I was thinking maybe it's the temperature hit that causes it but it's something related to battery maybe? Since disabling the battery driver helps sometimes but after a few hours, it might also hibernate again itself which sucks during an online gaming session.

**Comment by aleksamagicka** [comment]
May be unrelated to this, but the reason I wanted to control the fans was because of the high temperatures. What solved it is that I unparked all cores (there is a registry value for that), which did lower temps, and most importantly I undervolted the CPU (8750H) by around 85mV using Throttlestop (C-states disabled). It's working like a charm since then, and the fans are much less active than before. Temps are down, too (45C on idle).

In the meantime I've tried installing Intel chipset drivers that HP Support Assistant offered - same results.

**Comment by pibi** [comment]
I'm facing the same problem, although on a HP Spectre x360 13-ae0xx. I can also confirm that it is happening totally random.

**Comment by quevon24** [comment]
the problem persists, I'm testing with an HP 15-cb001la using this profile: HP Pavilion 17-ab240nd and if you turn the fans on at 100% it won't let you start the PC, it always hibernates moments after turning it on. anyone knows how to fix this issue?
