### ISSUE TITLE
Config for Yoga x380

### ISSUE THREAD

**Issue by smitzenmacher** [hirschmann/nbfc#779]
There is a bunch of complaints online about this particular model fan noise:
https://www.reddit.com/r/thinkpad/comments/98lxyt/x380_sounds_like_a_jet_plane_when_plugged_in/

Can you provide a config for this model please?

**Comment by benschi11** [comment]
I did a little research on that and found out, that the ec-register 0x85 does change everytime the fan speed is changing. But the wired thing is, that if I write to this register it immediately changes back to the old value and the fan does not change speed.
Any suggestions to go further.
Thanks

**Comment by alejrobinson** [comment]
I would like to pursue this as I have the opposite problem, when using the laptop plugged in, instead of ramping up the fan speed it just thermal throttles, leaving a lot of performance on the table (that is to say, it ramps up the fans, but nowhere near the max speed I found when updating BIOS).
I have some technical knowledge working with embedded electronics and Windows/Linux in general, but I would need some guidance as for how to proceed.
There may also be some useful information on HWiNFO64, since apparently it is able to read the EC and correctly identify the CPU temperature and fan speed (just tested it and the fan speed is correctly reported, thou the temperature might be of the chassis and not the CPU, but the fan speed seems to be tied to it).
![image](https://github.com/hirschmann/nbfc/assets/10033854/69ced72e-8fb1-4c1c-b6b8-b44249638725)
