### ISSUE TITLE
Connection refused for all commands

### ISSUE THREAD

**Issue by compliment** [hirschmann/nbfc#786]
**Describe the bug**
Connection refused for all commands.

**To Reproduce**
Any command 

**Expected behavior**
Work

**System information**
 - Archlinux  Linux 5.3.11
 - NBFC version  1.6.3.r21.gc8fd3d1-1

**Additional context**
I tried all solutions here on previous issue.
[NbfcServiceLog.2019-11-10.txt](https://github.com/hirschmann/nbfc/files/3846893/NbfcServiceLog.2019-11-10.txt)
[NbfcServiceLog.txt](https://github.com/hirschmann/nbfc/files/3846894/NbfcServiceLog.txt)
Edit; It was working on 2019-11-10 and before.
[NbfcServiceLog.txt](https://github.com/hirschmann/nbfc/files/3846909/NbfcServiceLog.txt)
[NbfcServiceLog.2019-11-03.txt](https://github.com/hirschmann/nbfc/files/3846910/NbfcServiceLog.2019-11-03.txt)
[NbfcServiceLog.2019-10-27.txt](https://github.com/hirschmann/nbfc/files/3846911/NbfcServiceLog.2019-10-27.txt)

**Comment by damufo** [comment]
Same problem on 

ubuntu 19.10 
nbfc version 1.6.3.0

<pre>
user@elitebook:/opt/nbfc$ mono nbfc.exe status -a
Connection refused
user@elitebook:/opt/nbfc$ systemctl status nbfc
● nbfc.service - NoteBook FanControl service
   Loaded: loaded (/etc/systemd/system/nbfc.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2020-01-03 09:15:56 CET; 9min ago
  Process: 2186 ExecStart=/opt/nbfc/nbfcservice.sh start (code=exited, status=127)

Xan 03 09:15:56 elitebook systemd[1]: nbfc.service: Service RestartSec=100ms expired, scheduling restart.
Xan 03 09:15:56 elitebook systemd[1]: nbfc.service: Scheduled restart job, restart counter is at 5.
Xan 03 09:15:56 elitebook systemd[1]: Stopped NoteBook FanControl service.
Xan 03 09:15:56 elitebook systemd[1]: nbfc.service: Start request repeated too quickly.
Xan 03 09:15:56 elitebook systemd[1]: nbfc.service: Failed with result 'exit-code'.
Xan 03 09:15:56 elitebook systemd[1]: Failed to start NoteBook FanControl service.
user@elitebook:/opt/nbfc$
<pre>

/etc/systemd/nbfc,service
<pre>
[Unit]
Description=NoteBook FanControl service

[Service]
ExecStart=/opt/nbfc/nbfcservice.sh start
ExecStop=-/opt/nbfc/nbfcservice.sh stop
Type=forking
PIDFile=/run/nbfc.pid
TimeoutStopSec=20
Restart=on-failure

[Install]
WantedBy=multi-user.target
</pre>

**Comment by bayasdev** [comment]
Fixed by installing mono-service4 then re-run sudo systemctl enable nbfc --now
NBFC is working for me after doing that

**Comment by bayasdev** [comment]
Proof:
![Captura de pantalla de 2020-06-09 17-52-45](https://user-images.githubusercontent.com/49411169/84208768-1a2b5180-aa7a-11ea-9bc5-586ebea3e050.png)

@hirschmann please update the wiki to add this required package

**Comment by matguidi** [comment]
Sorry, I am using Manjaro on a Huawei Matebook (which isn't in the list of laptops, btw). This is my machine:

```
CPU: Quad Core AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx (-MT MCP-) speed/min/max: 1222/1400/2100 MHz 
Kernel: 5.9.6-1-MANJARO x86_64 Up: 28m Mem: 3940.6/6950.8 MiB (56.7%) Storage: 476.94 GiB (35.3% used) Procs: 277 Shell: Bash 
inxi: 3.1.08
```

I also get the message "Connection refused", but I can't find the package you refer to (mono-service4). Any ideas about what I should install?

**Comment by damufo** [comment]
Try:
    
    $ sudo apt install mono-complete
    Dani
    O 08/11/20 ás 23:36, matguidi escribiu:
    
    
      
      Sorry, I am using Manjaro on a Huawei Matebook (which isn't in
        the list of laptops, btw). This is my machine:
      CPU: Quad Core AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx (-MT MCP-) speed/min/max: 1222/1400/2100 MHz 
Kernel: 5.9.6-1-MANJARO x86_64 Up: 28m Mem: 3940.6/6950.8 MiB (56.7%) Storage: 476.94 GiB (35.3% used) Procs: 277 Shell: Bash 
inxi: 3.1.08

      I also get the message "Connection refused", but I can't find
        the package you refer to (mono-service4). Any ideas about what I
        should install?
      —
        You are receiving this because you commented.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/hirschmann/nbfc/issues/786#issuecomment-723676087",
"url": "https://github.com/hirschmann/nbfc/issues/786#issuecomment-723676087",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by compliment** [comment]
Doesn't happen anymore with mono 6.12.0.107. 
Check the mono version.
