### ISSUE TITLE
HP Pavilion dv6 wrong temperature 

### ISSUE THREAD

**Issue by ahmedhamdy90** [hirschmann/nbfc#8]
Hi hirschmann,
I would like to report an issue that the program is reporting wrong CPU temperature for my laptop hp pavilion dv6.

I used to use another program for CPU temperature called "Core Temp", by monitoring the behaviour of both programs, your program is always adding (8~12) degree to the actual reading.

Can you please check?
Thank you very much.

**Comment by hirschmann** [comment]
Hi ahmedhamdy,

I need some more information about your hardware.
Please download [OpenHardwareMonitor](http://openhardwaremonitor.org/), generate a report (File --> Save report), upload it somewhere and post the link here.

**Comment by ahmedhamdy90** [comment]
Hi hirschmann,
Sorry for being late, I had exams.

Please find the report here:
http://www.mediafire.com/view/yw1nbz4g59k7v16/OpenHardwareMonitor.Report.txt

Please for anything else, I will be glad to help.

**Comment by hirschmann** [comment]
According to the report, Tjmax for your CPU is 100°C which should be right for a Core 2 processor.
Does CoreTemp use a different Tjmax to calculate the actual CPU temperature? Are you sure CoreTemp calculates the right temperature?

Also, the temperature NBFC shows is not really the current reading, but the average of all temperature readings in the last 6 seconds in order to compensate short temperature spikes.

**Comment by ahmedhamdy90** [comment]
So, you are suggesting that the other program has a wrong temperature value? Maybe, I actually can't tell who is the right one.
