### ISSUE TITLE
HP Spectre x360 13-aw0009nn 10th gen Ice Lake CONFIG

### ISSUE THREAD

**Issue by sensus261** [hirschmann/nbfc#806]
Hello, I'd like to know if someone found a workaround for a percentage manual fan control for this laptop.

For Windows 10 OS:
The existing config from the repository for the HP Spectre x360 Convertible 13-ae0xx has only 2 possible options : fans off or auto fans . The problem is that auto fans most likely inherit the behavior from the HP Command Centre (which doesnt work that well). 
The fans starts kicking in way too late (on performance profile, under moderate to heavy use the laptop stays at 90-95 degrees for a few minutes with fans at 0 RPM, then the fans kick in at about 50-60 percent of their max spin rate).
I wonder if someone discovered how to manually override the fan speeds in percentage. I'm asking this because it should be possible somehow...

**Comment by mrgoindol** [comment]
have same problem... (spectre x360 13 - aw0000)

**Comment by 9716cwr** [comment]
Yes, full support would be great. HP's fan management is horrible! ( HP Spectre x360 Conv13-aw0030ng ALL )

**Comment by etdecode** [comment]
Bios set values > HP Command Profile can read them and defines which profile to use.   
Note that if you are Throtlestop user, it will also limit Power Limit management.   
- cooling is like 7.5W fan threshold set at **45°C**
- recommended is about 10W fan threshold set at **60°C**
- performance is 15W should be **75°C**
exact value can be monitored with TS over PL window.  
Please note that NBFC cannot override fan control if the profile's threshold does not include the current temp.  
Remember that a 4.5 GHZ cpu has a TDP of rather 50W than the 25W from the marketing team, the cooling won't sustain this.  
 Typical load frequency is around 3GHz  

Unfortunately this system is **highly unreliable** so it can literally toast the CPU.
HP support is such a joke "If I understand correctly, you have an issue, please gimme some intel before I waste your time"

### Best workaround:
Set Hp command center to cooling (low °C threshold)
Use Throttlestop and into FIVR window tick "Extend power limit" once the extra tool is downloaded TS will be able to override Power Limits with fan ON (starts at 45°C actually).  
Bonus: TS can let you tweak the turbo and all core turbo to max cpu frequency ( ; 

### Workaround known issue: 
Due to Intel leaving backdoors on CPU, they have decided to disable the undervolting for newer laptops. As such running W10 insider build with late bios would like crash the system if undervolting is applied (green screen of death). To fix this, first wipe TS config.ini and avoid applying any undervolting when developping over W10 insider builds.

### No brainer tip:
1. Use ThrottleStop
2. Set a profile (battery) with **SPEEDSHIFT set to 255**. It will solve all turbo fan issues. (W10 & Defender can usually cook the cpu while installing update in background)
3. Make TS starts by setting a Scheduler shortcut (to bypass admin account prompt)
