### ISSUE TITLE
Trouble extracting DSDT

### ISSUE THREAD

**Issue by super-eye** [hirschmann/nbfc#836]
Hi, I'm trying to extract DSDT on DSDT Editor and it retuns: "java.io.IOException: Cannot run program "./iasl-linux": error=2, No such file or directory" I'm on Debian Buster
What I can do?
Regards

**Comment by hirschmann** [comment]
The reason for this issue is that the iasl binary which ships with the DSDT editor is a x86 binary and you try to run it on a x64 system without support for the i386 architecture.

You can either add support for x86 assemblies like this:
https://askubuntu.com/questions/522372/installing-32-bit-libraries-on-ubuntu-14-04-lts-64-bit
https://wiki.debian.org/Multiarch/HOWTO

**Or** simply install the x64 version of iasl:
`sudo apt install iasl`

And then replace the `iasl-linux` file in the DSDT editor folder with the following script:
```bash
#!/bin/bash
/usr/bin/iasl
```

Don't forget to set the executable bit for the script and run the DSDT editor as root.
