### ISSUE TITLE
Asus Zenbook UXVD

### ISSUE THREAD

**Issue by DrLoutre** [hirschmann/nbfc#85]
Sometimes, the actual speed does not change between being set at 12,5% or100%, it is always actually at (or near) 100%.

**Comment by Brisko007** [comment]
Got a similar issue for my UX32VD ... 

When the tool sets the fanspeed to 25% (or I set it manually to this value) the fan ramps up to full!

My workaround is to set the value for the low setting to 32.xxx instead of 28.xxx in the config file and restart the service so the 37,5% is triggered which works fine ... (a bit louder but way less than the 100% fan)

As it has worked without any problems before, maybe the last .net Framework Update OR a Microsoft Win 10 Update has screwed up the 25% fan setting ... 

If I get around to it, I'll investigate some more!
