### ISSUE TITLE
Request config for Lenovo Thinkbook 14-IML

### ISSUE THREAD

**Issue by estazz** [hirschmann/nbfc#866]
Hi guys I am looking for a suitable config file for my new Lenovo Thinkbook 14-IML.
I already tried the recommended config files but none seems to work properly.

Thanks in advance!

**Comment by dchekanov** [comment]
Hi, I have a sibling model, 14-IIL. The EC probe utility didn't show the register that is used to set the target fan speed, so I guess the fan can't be adjusted from the OS here. Or maybe you need to figure out the EC model and read its datasheet to find the register. And it could be different for your particular configuration. Anyway, if you can place the laptop on a stand so that the fan noise does not resonate from the surface right below it, acoustics should improve. It worked out pretty well for me.

**Comment by Karssadin** [comment]
> Hi, I have a sibling model, 14-IIL. The EC probe utility didn't show the register that is used to set the target fan speed, so I guess the fan can't be adjusted from the OS here. Or maybe you need to figure out the EC model and read its datasheet to find the register. And it could be different for your particular configuration. Anyway, if you can place the laptop on a stand so that the fan noise does not resonate from the surface right below it, acoustics should improve. It worked out pretty well for me.

halo,  can u share the 14-IIL config file for me? I wanna to try it on 15-IIL. Thank u.

**Comment by dchekanov** [comment]
> > Hi, I have a sibling model, 14-IIL. The EC probe utility didn't show the register that is used to set the target fan speed, so I guess the fan can't be adjusted from the OS here. Or maybe you need to figure out the EC model and read its datasheet to find the register. And it could be different for your particular configuration. Anyway, if you can place the laptop on a stand so that the fan noise does not resonate from the surface right below it, acoustics should improve. It worked out pretty well for me.
> 
> halo, can u share the 14-IIL config file for me? I wanna to try it on 15-IIL. Thank u.

Hi, as I wrote in the quoted comment, the utility didn't show the required register, so there's no config file to share, sorry.
