### ISSUE TITLE
Get write/read register with RW-everything

### ISSUE THREAD

**Issue by Katzenwerfer** [hirschmann/nbfc#913]
How do you know wich hex value is your fan?

**Comment by Lamb3** [comment]
If you have trouble identifying which register your fan is located, then you need to do some stress test on the CPU just to ramp up the fans and monitor the values in all those registers by way of EC-probe. I don't use that method since I really don't know how to do it properly.

**I, however, went the unconventional way of identifying it by;**
1. Starting up a game and playing it just till it ramps up the fan speed up to the max (if it reaches it)
2. Record a video showing RWEverything EC table for a good 20 seconds.
3. Exit the game to reduce load so as to induce lower fan speeds.
4. Record a video of the EC table immediately after quitting the game for 30 seconds (or 1 minute if you feel like it)
5. Compare both videos and find the distinct changes to values in the EC table window.

At step 5, you will notice that there should be value(s) that decreases each time the fan speed slows down (as can be heard through the video recording). These can be the CPU temperature and fan speed (can also be 2 registers instead of just 1 if your motherboard has 2 independent fans).

On my Gigabyte laptop, I only have 1 register that correlates with fan speeds and the temperature readings are close to that same register. The registers in your laptop may very well differ from mine but do look for patterns to identify your fan.

**Comment by Katzenwerfer** [comment]
I'll check it out.
sorry if I answered later, I was too lazy to check :p
