### ISSUE TITLE
Add ASUS X550VX.. Please.. I'm desperate..

### ISSUE THREAD

**Issue by thegreatmihai** [hirschmann/nbfc#950]
**Information about my laptop:**

Model - X550VX
Manufacturer - ASUSTeK COMPUTER INC.
DSDT Editor Code - https://mega.nz/file/Zod0RI6A#pZxuk_R9s-abHbhbhOyuuHoujWXTNZqI5y6Kr86wLTE

All that I know.. 

I want to hear my fan louder and be at this 100% power..

I'm ready to give more information about this..

**Comment by g34rn1nja** [comment]
I tried to find your schemetic, took my time but wasn't able to. I got the EC name though, if you want you can make a request for the schemetic on https://badcaps.net

I looked at the .txt you shared, and also took a look at your DSDT, found some interesting lines, I believe that you'll find the read and write registers if you look at the DSDT enough, but you could also try to get a tool that display your BIOS information, using a proprietery tool for your motherboard's BIOS, I use Insyde BIOS Editor for mine since I got an Insyde BIOS, it showed some information on mine, didn't get it to work yet, started an issue on here and got no responses still. Anyways, your DSDT looks promosing, you could use it to find the registers, get the register values from the  Fan variables in it and  them with ec-probe.exe output while using the provided PC usage increaser/"CPU & RAM torture" too mentioned in the Wiki to up your fan speed.

That's pretty much it, in a nutshell, either post a request on badcaps.net or try to find the registers through the others DSDT ways, which you could combine with proping the registers you believe are for the Fan, where you're gonna have to read the values that you get the DSDT as well as using the "torture" method to up your usage. it's best if you can get the schemetic, you can also try request it a company that sells the EC, I found one in Hong Kong
![download](https://user-images.githubusercontent.com/68093058/88054705-5360e200-cb4d-11ea-842e-0e6fe7cfe8c9.jpg)

P.s: your EC's manufacturer is NetSwap, and you can emit the a from the of the model when Google searching

**Comment by g34rn1nja** [comment]
I tried to find your schematic, took my time but wasn't able to. I got the EC name though, if you want you can make a request for the schematic on https://badcaps.net

I looked at the .txt you shared, found some interesting lines, I believe that you'll find the read and write registers if you look at the DSDT enough, but you could also try to get a tool that display your BIOS information, using a proprietery tool for your motherboard's BIOS, I use Insyde BIOS Editor for mine since I got an Insyde BIOS, it showed some information on mine, didn't get it to work yet, started an issue on here and got no responses still. Anyways, your DSDT looks promosing, you could use it to find the registers, get the register values from the Fan variables in it and them with ec-probe.exe output while using the provided PC usage increaser/"CPU & RAM torture" too mentioned in the Wiki to up your fan speed.

That's pretty much it, in a nutshell, either post a request on badcaps.net or try to find the registers through the others DSDT ways, which you could combine with proping the registers you believe are for the Fan, where you're gonna have to read the values that you get the DSDT as well as using the "torture" method to up your usage. it's best if you can get the schematic, you can also try request it a company that sells the EC, I found one in Hong Kong
download

P.s: your EC's manufacturer is NetSwap, and you can emit the a from the of the model when Google searching
![download](https://user-images.githubusercontent.com/68093058/88054978-c407fe80-cb4d-11ea-9f2a-b85352bc1ef8.jpg)

**Comment by thegreatmihai** [comment]
I really don't know what to do.. :(
I read the tutorial from the "How to create a NBFC config" and I extracted what I saw and was in my knowledge :D
I'm not a native in english but what I read fried my brain, sorry.. If I known how to do this stuff.. I would never put this issue.. so please.. if u can make it short and simple to understand.. would be awesome.. to know what to do <3

edit: Not very knowledgeable about this kind of stuff.. ;(

**Comment by g34rn1nja** [comment]
The important part is finding the read, write, min and mix (Fan speed)
registers. That's the main part. I found a variable in the .txt called "FAN
RPM", that's for the fan speed, try using its register as the write
register, use ec-probe to set the value. You need to try to find the
registers yourself, there's no way around it, because I don't have the same
laptop and testing is need. if you want we could try on Teamviewer

**Comment by thegreatmihai** [comment]
I want to try on Teamviewer if possible

**Comment by g34rn1nja** [comment]
Cool, schedule an event on Google calenderand invite me to it, then you can
email me your ID and password once you have it running and i'll join

**Comment by thegreatmihai** [comment]
I don't know ur e-mail

**Comment by g34rn1nja** [comment]
There you go: thegearninjas@gmail.com

:)

**Comment by logix10** [comment]
hey guys if you managed to make it work is it possible to link the config file i'm desperate as well, xD
it would be much appreciated

**Comment by ersin3381** [comment]
Hey, I need a config for x550vx. Do you guys found a solution?
