### ISSUE TITLE
HP cw1xxx Ryzen 5 3500U stuck at 0.4 ghz.  

### ISSUE THREAD

**Issue by tall414** [hirschmann/nbfc#954]
My CPU is locked at 0.4 ghz across all cores, even though temps are all below 40c.  

I started picking similar HP devices because mine was not an option.  and it started to run SUPER slow. 

I expected it to make my fan louder.

Windows 10 1909

My brand new laptop is now bricked. Help would be much appreciated.

**Comment by ghost** [comment]
No it is far from bricked. Just try restarting, unplugging your power adapter and plugging it back in. 

And when this does not work: unplug the power adapter, turn your notebook off, press down the on button for 15 seconds, plug the power adapter back in and press the on button normally

Also: There is NO working config in this github repo for HP Pavilion 15 cw/cs, so don't even try. I have a HP Pavilion 15-cwxxx and i made my own config working weeks on it. It works okay for me.

**Comment by Hurley2017** [comment]
I have the same cpu but the laptop is Asus Vivobook X512DA and it is alwaays stuck at 0.4 ghz, Its really slow. Temparature is normmal. I dont think that maybe causing this issue, Battery is ok, charger is ok, its happening on both ac power and battery power. i am worried sick. I have thins only laptop and it's stuck. I wonder ASUS does this after bios upgrade, so that you have to buy new laptop. This is straight cruelty

**Comment by WhebertSouza** [comment]
> I have the same cpu but the laptop is Asus Vivobook X512DA and it is alwaays stuck at 0.4 ghz, Its really slow. Temparature is normmal. I dont think that maybe causing this issue, Battery is ok, charger is ok, its happening on both ac power and battery power. i am worried sick. I have thins only laptop and it's stuck. I wonder ASUS does this after bios upgrade, so that you have to buy new laptop. This is straight cruelty

did you find out what it could be? I have the same problem.

**Comment by Hurley2017** [comment]
I found the issue and kind of fixed it. Do the following and this will be forever fixed. Freshly install Windows of your choice. Disconnect from internet. [for blocking automatic driver installation.] Better use a lite windows which disables updates. then manually find drivers that were released when your laptop is released. If you had a CD driver you are lucky. otherwise Scrape it from the internet. Then install the drivers. Do not install AMD gpu drivers yet. Restart then charge your laptop to 80% + then install your gpu driver from AMD website (manually choose the driver). This method works and I know why it works in details. So feel free to connect with me I can explain. Also do not keep your laptop with 0%(dead) state for more than 12 hours. Also if you are a heavy user I recommend using your laptop on AC. Battery has a particular issue to do with the down clocking. for context Main CULPRIT = {PROCHET_EXT} an asshole interrupt that literally makes your computer clock at 400 Mhz.

**Comment by Erruar** [comment]
@tall414 @Hurley2017 use this solution.
https://github.com/Erruar/Saku-Overclock/wiki/FAQ#fix-04-ghz-on-ryzen-mobile-2000-3000th-lines-questions

**Comment by haseakash** [comment]
@Hurley2017 : So after installing fresh windows and after fully disabled automatic driver update both from windows update and hardware using WUB app. so next step is install only 1st released drivers ? i got that but here ther is only one driver for both chipset and gpu on HP site . so do you mean install other drivers skipping this ?  or here have to install chipset drivers official ?   or skipping it after 80% battery install gpu driver of AMD site directly ?

**Comment by Hurley2017** [comment]
Found the exact problem, and I got a permanent solution on these, PROCHET_EXT is often triggered when your bios is uncomfortable sort of (cause : heat, bad connections, temp, and even wrong config such as wrong date), in my case, the problem narrowed down to wrong date as i was running out of CMOS juice, I changed the battery and now, the problem is gone forever(in the last 6 months I did not face the issue). Please try this solution if your bios keeps getting reset after a softboot or being dead for 1 or 2 hours. Also, keep the battery plugged in even it says 100%, atleast for 2 hour excess, that ought to do the job

**Comment by Erruar** [comment]
@Hurley2017 Oh my god, man! This could actually be the root cause of all this! But on my laptop CMOS battery isn't exist, CMOS voltage becomes from usual battery, and it's died last time (63% wear level). And this can be actually issue! Man, you're a brilliant. I'll try it on several laptops with 0,4 GHz issue and say you will it helps.

**Comment by Erruar** [comment]
@Hurley2017 I've been testing this method and on three my laptops disconnecting the battery helps. But all them have Ryzens 2000-3000 lines. I have another laptop but with Ryzen 7 4800H and this method doesn't help at all... 0,4 GHz is still there, but it actually works on three laptops that I tested. God damn thank you so much

**Comment by Hurley2017** [comment]
@Erruar I am glad that it works for you, but on the laptop having R7 4800H, could you please monitor the interrupts right after boot, If I find some irregular interrupts, I can go around and see what would be the problem, You can do it yourself though, just not much information is available as this interrupt related issues are very uncommon. Thanks

**Comment by Erruar** [comment]
@Hurley2017 what did you mean "monitor the interrupts"? After boot CPU is always working on 0,4 GHz, Prochot Ext is triggered True always. I tried running it without battery but it doesn't helped, sadly. And this laptop is also haven't external CMOS battery, but on laptops with 2000-3000 Ryzens disconnecting the battery really helps, even if they haven't CMOS battery. So on 4800H laptop 0,4 GHz is always triggered without normal CPU frequency, and boot time is so long

**Comment by fireshrimp-waterfall** [comment]
> [@tall414](https://github.com/tall414) [@Hurley2017](https://github.com/Hurley2017) use this solution. https://github.com/Erruar/Saku-Overclock/wiki/FAQ#fix-04-ghz-on-ryzen-mobile-2000-3000th-lines-questions

thank you this solution is work for me damn after 2 day for check any problem(power battery,power adapter,temperature,fanspeed,thermap grace,keyboard)

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/3c58404c-0d4a-4b4e-8ebf-4fc43f8f466a" />

**Comment by fireshrimp-waterfall** [comment]
i thing this problem is on battery after use sakuOverclock and plugin battery adapter and use some office programing around 3 or 5 hour battery indicator show 60 to 70% not rise to 99% or 100%

**Comment by Erruar** [comment]
@fireshrimp-waterfall thanks for your feedback! 
I think the problem is in hardware. It can be battery but I can't say anything about that. No one tried completely replacing battery to a new one. But removing battery helps actually (not for all laptops). I think the problem can be in charger chip or even embedded controller. Someone even fixed that issue by replacing resistors near VRM chip
